// Sistema de traducción (i18n) de toda la app.
// Para añadir un idioma: copia un bloque y traduce los textos.
// Para añadir un texto: agrégalo con su clave en TODOS los idiomas.

export const IDIOMAS = {
  es: { nombre: "Español", bandera: "🇪🇸" },
  en: { nombre: "English", bandera: "🇬🇧" },
  pt: { nombre: "Português", bandera: "🇧🇷" },
  fr: { nombre: "Français", bandera: "🇫🇷" },
};

const T = {
  es: {
    // Cabecera y búsqueda
    tagline: "Tu itinerario perfecto en cualquier ciudad del mundo",
    buscarPlaceholder: "Ciudad, País (ej. Madrid, España)",
    buscar: "Buscar",
    // Inicio
    heroTitulo: "Tu viaje, planeado en segundos",
    heroTexto:
      "Itinerario día a día con los mejores lugares, fotos, restaurantes y cómo moverte entre ellos. Todo aquí, sin salir de la app.",
    benDiaTitulo: "Día por día",
    benDiaTexto: "Reparte los lugares según tu tiempo",
    benGpsTitulo: "GPS en vivo",
    benGpsTexto: "Te avisa si vas adelantado o atrasado",
    benComerTitulo: "Comer y salir",
    benComerTexto: "Restaurantes, cafés y vida nocturna",
    benLlegarTitulo: "Cómo llegar",
    benLlegarTexto: "Transporte, tiempo y costo entre puntos",
    pruebaPopular: "Prueba con un destino popular:",
    // Configuración
    dias: "Días",
    horasDia: "Horas/día",
    recalcular: "Recalcular",
    diurno: "Diurno",
    nocturno: "Nocturno",
    diurnoDesc: "Monumentos, museos y paseos",
    nocturnoDesc: "Bares, miradores y vida nocturna",
    lugares: "lugares",
    // Categorías
    cat_imperdibles: "Imperdibles",
    cat_restaurantes: "Restaurantes",
    cat_cafes: "Cafés",
    cat_bares: "Bares / Noche",
    cat_miradores: "Miradores",
    cat_museos: "Museos",
    cat_monumentos: "Monumentos",
    cat_parques: "Parques",
    cat_estadios: "Estadios",
    // Itinerario
    dia: "Día",
    paradas: "paradas",
    enTotal: "en total",
    visitas: "Visitas",
    traslados: "Traslados",
    empezarGps: "Empezar día con seguimiento GPS",
    llegueSiguiente: "Llegué a la siguiente",
    terminar: "Terminar",
    parada: "Parada",
    sinParadas:
      "No hay paradas para este día con el tiempo configurado. Sube las horas por día o reduce el número de días.",
    cargandoLugares: "Buscando los mejores lugares…",
    sinResultados:
      "No encontramos lugares de esta categoría cerca del centro. Prueba otra categoría o toca Recalcular.",
    cargando: "Cargando…",
    // Acciones de parada
    verFoto: "Ver foto y cómo llegar",
    cambiar: "Cambiar",
    quitar: "Quitar",
    // Detalle del lugar
    comoLlegar: "Cómo llegar",
    desdeTuUbicacion: "desde tu ubicación",
    activaGps:
      "Activa el GPS (abajo en la app) para ver el transporte y el tiempo exactos desde donde estás.",
    estasA: "Estás a",
    deAqui: "de aquí. Elige cómo llegar:",
    desdeCentro: "del centro de",
    verRuta: "Ver ruta",
    recomendado: "recomendado",
    aproxAviso:
      "Tiempos y costos aproximados. La ruta se dibuja en el mapa de la app.",
    // GPS
    activarGps: "Activar GPS para verme en el mapa y calcular tiempos en vivo",
    activo: "activo",
    // Estado de tiempo
    atrasado: "Vas {n} min atrasado",
    adelantado: "Vas {n} min adelantado",
    enHora: "Vas en hora",
    // Transporte
    caminar: "Caminar",
    metroBus: "Metro / Bus",
    bici: "Bici",
    taxiApp: "Taxi / App",
    gratis: "Gratis",
    // Login / perfil
    hola: "Hola",
    entrar: "Entrar",
    salir: "Salir",
    inicio: "Inicio",
    tuNombre: "¿Cómo te llamas?",
    comenzar: "Comenzar",
    entrarGoogle: "Continuar con Google",
    oContinuar: "o",
    authEntrarEmail: "Entrar con email",
    authTuEmail: "Tu correo electrónico",
    authEnviarCodigo: "Enviar código",
    authVerificar: "Verificar y entrar",
    authVolver: "Volver",
    authCambiarEmail: "Cambiar el email",
    authMandamosCodigo: "Te enviamos un código de 6 dígitos a",
    authComoLlamamos: "¿Cómo quieres que te llamemos? (opcional)",
    authErrorEmail: "Revisa el formato del email.",
    authErrorEnvio: "No pudimos enviar el código. Intenta de nuevo.",
    authErrorCodigo: "Escribe los 6 dígitos del código.",
    authErrorCodigoMal: "Código incorrecto o expirado.",
    idioma: "Idioma",
    footer: "Datos de OpenStreetMap y Wikipedia",
    // Afiliados / reservas
    afTitulo: "Reserva tu viaje",
    afTours: "Tours y experiencias",
    afToursDesc: "Actividades con guía cerca de tu ruta",
    afHoteles: "¿Dónde dormir?",
    afHotelesDesc: "Hoteles cerca de tu itinerario",
    afVuelos: "Vuelos",
    afVuelosDesc: "Encuentra vuelos a tu destino",
    afReservar: "Ver opciones",
    afTourCerca: "Reserva un tour aquí cerca",
    afESIM: "eSIM internacional",
    afESIMDesc: "Datos al llegar con Airalo",
    afSeguro: "Seguro de viaje",
    afSeguroDesc: "Cobertura médica + cancelación",
    paywallTitulo: "Hazte Pro",
    paywallMotivoGuardar: "Estás guardando tu segundo viaje. Con Pro guardas todos los que quieras, sincronizados en todos tus dispositivos.",
    paywallMotivoPDF: "Exporta tu itinerario como PDF para llevarlo offline.",
    paywallMotivoAlerta: "Recibe alerta cuando el vuelo baje de cierto precio.",
    paywallMotivoGrafico: "Mira el historial completo de precios mes por mes.",
    paywallMotivoCompartir: "Comparte tu plan con un enlace público.",
    paywallAnio: "año",
    paywallMes: "mes",
    paywallUnaSolaVez: "una sola vez",
    paywallAhorroAnual: "Ahorra 60% vs mensual",
    paywallLifetime100: "Oferta de lanzamiento · primeros 100",
    paywallV1: "Viajes ilimitados sincronizados",
    paywallV2: "Export PDF y compartir",
    paywallV3: "Alertas de precios ilimitadas",
    paywallV4: "Historial completo + sin anuncios",
    paywallVAlt1: "Todo lo de Pro mientras esté activo",
    paywallVAlt2: "Cancela cuando quieras",
    paywallVLife1: "Pro de por vida, sin renovaciones",
    paywallEmpezar: "Empezar",
    paywallSinAtaduras: "Cancela cuando quieras",
    paywallDevolucion: "Devolución 14 días",
    paywallNecesitaLogin: "Ingresa con tu email primero para asociar la compra a tu cuenta.",
    paywallNoConfigurado: "El checkout aún no está configurado. Avísanos.",
    alertaBoton: "Avísame si baja",
    alertaModalEyebrow: "Alerta de precio",
    alertaModalTitulo: "Avísame cuando {ciudad} baje",
    alertaModalSub: "Te llega un email apenas el detector vea un vuelo bajo tu umbral.",
    alertaUmbral: "Te aviso si el precio baja de:",
    alertaActualHoy: "Hoy:",
    alertaConfirmar: "Crear alerta",
    alertaCreada: "¡Alerta activada!",
    alertaCreadaSub: "Te avisaremos por email apenas el precio baje.",
    alertaCerrar: "Cerrar",
    alertaError: "Algo falló. Intenta de nuevo.",
    alertaAuthTitulo: "Necesitas tu email para alertas",
    alertaAuthSub: "Inicia sesión rápido y te asociamos la alerta a tu cuenta.",
    alertaEntrar: "Iniciar sesión",
    alertaPrivacidad: "Tu email se usa solo para esta alerta. Cancela cuando quieras.",
    menuUsuarioAria: "Menú de usuario",
    menuMisAlertas: "Mis alertas",
    menuSinAlertas: "Aún no tienes alertas activas.",
    menuBorrarAlerta: "Borrar",
    menuHazteProCTA: "Hazte Pro",
    menuGestionarPro: "Gestionar suscripción",
    menuPlanes: "Ver planes",
    afNota: "Algunos enlaces son de afiliados: si reservas, podemos ganar una comisión sin costo extra para ti.",
    saludoManana: "Buenos días",
    saludoTarde: "Buenas tardes",
    saludoNoche: "Buenas noches",
    // Presupuesto
    presupEyebrow: "Planifica por presupuesto",
    presupBoton: "¿Adónde viajar con mi presupuesto?",
    presupTitulo: "Viaja con tu presupuesto",
    presupSub: "Mira a dónde puedes ir con lo que tienes",
    presupTuPresup: "Tu presupuesto total",
    presupPersonas: "Personas",
    presupPersonaS: "persona",
    presupPersonasP: "personas",
    presupRegion: "¿A qué región?",
    presupDestinos: "destinos a tu alcance",
    presupVuelo: "Vuelo (ida y vuelta)",
    presupPrecioReal: "Precio real",
    presupBuscarReal: "Buscar precio real",
    presupBuscandoReal: "Buscando precios en vivo…",
    presupNoEncontrado: "Sin oferta en vivo para este destino",
    presupVerAviasales: "Buscar en Aviasales",
    presupVerGoogle: "Buscar en Google",
    presupCompararGoogle: "Comparar en Google Vuelos",
    presupEstimado: "Estimado",
    presupOfertaPara: "Oferta para",
    presupHospedaje: "Hospedaje",
    presupComida: "Comida",
    presupTransporte: "Transporte local",
    presupExtras: "Actividades y extras",
    presupTeSobra: "Te sobra",
    presupTeFalta: "Te falta",
    presupAlcanza: "alcanza para",
    presupPlanear: "Planear",
    presupVerVuelos: "Ver vuelos",
    presupAviso:
      "Costos promedio orientativos para un turista de gama media (USD). Los vuelos son aproximados desde Colombia; confirma el precio real con el detector de vuelos.",
    // Diseño / etiquetas
    heroEyebrow: "Planifica tu próxima aventura",
    destinosEyebrow: "Inspiración",
    recomendadoEyebrow: "Pensamos que te gustaría",
    recomendadoTitulo: "Destinos para {nombre}",
    ideasEyebrow: "Ideas para empezar",
    ideaPresupuesto: "Mi presupuesto",
    heroEyebrowBudget: "Plan tu viaje desde {pais}",
    heroH1Budget: "¿Cuánto tienes para gastar?",
    heroSubBudget: "Te decimos a dónde ir, cuándo es más barato y armamos el plan día por día.",
    heroVerOpciones: "Ver opciones",
    heroOSabesDestino: "o si ya sabes a dónde",
    descargarPDF: "Descargar como PDF",
    viajerosHoy: "viajeros hoy",
    viajeroEnLinea: "viajero en línea",
    viajerosEnLinea: "viajeros en línea",
    cargandoFase1: "Buscando lugares cerca del centro…",
    cargandoFase2: "Explorando hasta 70 km a la redonda…",
    cargandoFase3: "Puliendo fotos y rutas…",
    // Presupuesto · modos y ruta
    presupModoDestino: "Un destino",
    presupModoRuta: "Ruta multiciudad",
    presupRutaSub: "Arma una ruta de varias ciudades que entre en tu presupuesto",
    presupDesdeCiudad: "Empezar la ruta por",
    presupSalesDesde: "Sales desde",
    presupSalesDesdeNota: "Precios reales escaneados desde estos aeropuertos cada 3 horas.",
    presupCoberturaTitulo: "Cobertura limitada",
    presupCoberturaAviso: "El detector aún no escanea precios desde {pais}. Mostramos estimados orientativos; los precios reales se buscan en vivo cuando abres una ciudad.",
    presupAhorroDesde: "Desde {origen} te ahorras",
    presupRutaTitulo: "Tu ruta recomendada",
    presupOtraRuta: "Otra ruta",
    presupRutaCiudades: "ciudades",
    presupRutaDias: "días",
    presupNoRuta:
      "No encontramos una ruta dentro de tu presupuesto aquí. Sube el presupuesto o los días, o elige otra región.",
    presupVueloIntl: "Vuelo internacional (ida y vuelta)",
    presupEntreCiudades: "Transporte entre ciudades",
    presupNoches: "noches",
    // Ofertas de vuelos
    ofertasEyebrow: "Alertas de precio",
    ofertasTitulo: "Vuelos baratos desde Colombia",
    ofertasSub: "Mejores precios detectados desde Bogotá y Medellín hacia el mundo, actualizados cada pocas horas.",
    ofertasTodos: "Todos",
    ofertasGanga: "Oferta",
    ofertasIdaVuelta: "ida y vuelta",
    ofertasPlanear: "Planear",
    ofertasActualizado: "Actualizado",
    ofertasHaceMin: "visto hace {n} min",
    ofertasHaceHoras: "visto hace {n} h",
    ofertasActualizado: "Precios actualizados",
    ofertasHaceDias: "visto hace {n} d",
    ofertasAprox: "Precio aproximado",
    ofertasComparar: "Comparar en Google",
    ofertasViajerosVieron: "viajeros lo buscaron",
    ofertasMisFechas: "Buscar en mis fechas",
    fechaIda: "Ida",
    fechaVuelta: "Vuelta",
    limpiar: "Limpiar",
    cuandoEyebrow: "Planifica tus fechas",
    cuandoTitulo: "¿Cuándo quieres viajar?",
    guardarViaje: "Guardar",
    guardado: "Guardado",
    misViajesEyebrow: "Tus planes",
    misViajesTitulo: "Mis viajes guardados",
    misViajesReabrir: "Reabrir",
    misViajesEliminar: "Eliminar",
    misViajesSync: "Sincronizado",
    // Requisitos de entrada
    reqTitulo: "Requisitos de entrada a",
    reqTuPasaporte: "Tu pasaporte:",
    reqVisa: "Visa",
    reqVisaNota: "Para turismo/estancias cortas. Las condiciones pueden variar.",
    req_sinvisa: "Sin visa",
    req_sinvisaDias: "Sin visa · {n} días",
    req_llegada: "Visa al llegar",
    req_evisa: "Visa electrónica (e-visa)",
    req_eta: "Autorización electrónica (ETA)",
    req_requerida: "Visa requerida (tramítala antes)",
    req_noadmision: "Ingreso no permitido",
    req_mismopais: "Es tu país",
    req_desconocido: "Consulta los requisitos",
    reqPasaporte: "Pasaporte",
    reqPasaporteNota: "Vigente · mín. 6 meses recomendado",
    reqSalud: "Salud",
    reqFiebreSi: "Puede exigirse certificado de fiebre amarilla",
    reqFiebreNo: "Sin vacunas obligatorias frecuentes",
    reqVerOficial: "Ver requisitos oficiales",
    reqVerSalud: "Vacunas y salud",
    reqDatosPais: "Datos útiles del país",
    reqMoneda: "Moneda",
    reqIdioma: "Idioma",
    reqCapital: "Capital",
    reqHuso: "Huso horario",
    reqConduccion: "Se conduce por",
    reqTelefono: "Código tel.",
    reqIzquierda: "Izquierda",
    reqDerecha: "Derecha",
    reqEnchufe: "Enchufe",
    reqEstaciones: "Estaciones",
    estac_norte: "Verano jun–ago · Invierno dic–feb",
    estac_sur: "Verano dic–feb · Invierno jun–ago",
    estac_tropical: "Tropical (poca variación)",
    reqAgua: "Agua del grifo",
    reqPropina: "Propina",
    agua_potable: "Potable",
    agua_precaucion: "Mejor embotellada",
    agua_no: "No potable",
    prop_no: "No se acostumbra",
    prop_incluido: "Suele ir incluida",
    prop_diez: "~10% habitual",
    prop_veinte: "15–20% esperada",
    reqDisclaimer: "Información referencial. Los requisitos cambian; confirma siempre con la embajada/consulado y fuentes oficiales antes de comprar o viajar.",
    reqFuente: "Fuente",
    ofertasFuente: "Precios de referencia",
    todosLugares: "Todos los lugares",
    agregar: "Agregar",
    presupBuscarCiudad: "Buscar ciudad o país…",
    presupExcluidas: "Excluidas",
    presupExcluir: "Quitar esta ciudad de la ruta",
    // Asesor de viajes (chat IA)
    asesorBoton: "Asesor de viajes",
    asesorTitulo: "Brújula · Asesor de viajes",
    asesorSubtitulo: "Tu guía con IA",
    asesorSaludo: "¡Hola{nombre}! Soy Brújula 🧭, tu asesora de viajes. Cuéntame tu presupuesto, fechas o qué te gustaría conocer y te armo opciones.",
    asesorPlaceholder: "Pregúntame a dónde viajar…",
    asesorError: "Tuve un problema para responder. Intenta de nuevo.",
    asesorSinClave: "El asesor con IA aún no está activado. Para encenderlo, agrega tu clave ANTHROPIC_API_KEY en Vercel (Settings → Environment Variables) y vuelve a desplegar.",
    asesorModoGuia: "Guía gratis (sin costo)",
    asesorTabGuia: "Guía",
    asesorTabIA: "IA",
    asesorAvisoIA: "Modo IA: conversación libre con Claude. Consume créditos de la API.",
    guiaSaludo: "¡Hola{nombre}! Soy tu guía 🧭. Te armo una ruta sin costo. Primero: ¿a qué región quieres viajar?",
    guiaPreguntaPresupuesto: "¿Cuál es tu presupuesto total?",
    guiaPreguntaDias: "¿Cuántos días tienes?",
    guiaAquiRuta: "Esta ruta te cabe 👇",
    guiaSinRuta: "Con esos datos no encontré una ruta dentro del presupuesto. Prueba subir el presupuesto o los días, o elige otra región.",
    guiaVerPresupuesto: "Ver presupuesto completo",
    guiaReiniciar: "Empezar de nuevo",
    asesorEj1: "¿3 días en Lisboa?",
    asesorEj2: "¿Playa barata en diciembre?",
    asesorEj3: "¿Qué hago en Roma?",
    verMas: "Ver más",
    verMenos: "Ver menos",
    ajustarViaje: "Ajustar viaje",
    compartir: "Compartir",
    copiado: "¡Copiado!",
    miViajeA: "Mi viaje a",
    hechoCon: "Hecho con",
  },

  en: {
    tagline: "Your perfect itinerary in any city in the world",
    buscarPlaceholder: "City, Country (e.g. Madrid, Spain)",
    buscar: "Search",
    heroTitulo: "Your trip, planned in seconds",
    heroTexto:
      "Day-by-day itinerary with the best places, photos, restaurants and how to get around. All here, without leaving the app.",
    benDiaTitulo: "Day by day",
    benDiaTexto: "Splits places to fit your time",
    benGpsTitulo: "Live GPS",
    benGpsTexto: "Tells you if you're ahead or behind",
    benComerTitulo: "Eat & go out",
    benComerTexto: "Restaurants, cafés and nightlife",
    benLlegarTitulo: "How to get there",
    benLlegarTexto: "Transport, time and cost between points",
    pruebaPopular: "Try a popular destination:",
    dias: "Days",
    horasDia: "Hours/day",
    recalcular: "Recalculate",
    diurno: "Daytime",
    nocturno: "Nighttime",
    diurnoDesc: "Monuments, museums and walks",
    nocturnoDesc: "Bars, viewpoints and nightlife",
    lugares: "places",
    cat_imperdibles: "Must-see",
    cat_restaurantes: "Restaurants",
    cat_cafes: "Cafés",
    cat_bares: "Bars / Night",
    cat_miradores: "Viewpoints",
    cat_museos: "Museums",
    cat_monumentos: "Landmarks",
    cat_parques: "Parks",
    cat_estadios: "Stadiums",
    dia: "Day",
    paradas: "stops",
    enTotal: "total",
    visitas: "Visits",
    traslados: "Transfers",
    empezarGps: "Start day with GPS tracking",
    llegueSiguiente: "I reached the next one",
    terminar: "Finish",
    parada: "Stop",
    sinParadas:
      "No stops for this day with the set time. Increase hours per day or reduce the number of days.",
    cargandoLugares: "Finding the best places…",
    sinResultados:
      "We couldn't find places in this category near the center. Try another category or tap Recalculate.",
    cargando: "Loading…",
    verFoto: "See photo and how to get there",
    cambiar: "Change",
    quitar: "Remove",
    comoLlegar: "How to get there",
    desdeTuUbicacion: "from your location",
    activaGps:
      "Turn on GPS (below in the app) to see exact transport and time from where you are.",
    estasA: "You're",
    deAqui: "away. Choose how to get there:",
    desdeCentro: "from the center of",
    verRuta: "See route",
    recomendado: "recommended",
    aproxAviso:
      "Approximate times and costs. The route is drawn on the app's map.",
    activarGps: "Turn on GPS to see myself on the map and track times live",
    activo: "active",
    atrasado: "You're {n} min behind",
    adelantado: "You're {n} min ahead",
    enHora: "You're on time",
    caminar: "Walk",
    metroBus: "Metro / Bus",
    bici: "Bike",
    taxiApp: "Taxi / App",
    gratis: "Free",
    hola: "Hi",
    entrar: "Sign in",
    salir: "Sign out",
    inicio: "Home",
    tuNombre: "What's your name?",
    comenzar: "Start",
    entrarGoogle: "Continue with Google",
    oContinuar: "or",
    authEntrarEmail: "Sign in with email",
    authTuEmail: "Your email",
    authEnviarCodigo: "Send code",
    authVerificar: "Verify and enter",
    authVolver: "Back",
    authCambiarEmail: "Change email",
    authMandamosCodigo: "We sent a 6-digit code to",
    authComoLlamamos: "What should we call you? (optional)",
    authErrorEmail: "Check the email format.",
    authErrorEnvio: "Couldn't send the code. Try again.",
    authErrorCodigo: "Enter all 6 digits of the code.",
    authErrorCodigoMal: "Wrong or expired code.",
    idioma: "Language",
    footer: "Data from OpenStreetMap and Wikipedia",
    // Afiliados / reservas
    afTitulo: "Book your trip",
    afTours: "Tours & experiences",
    afToursDesc: "Guided activities near your route",
    afHoteles: "Where to stay?",
    afHotelesDesc: "Hotels near your itinerary",
    afVuelos: "Flights",
    afVuelosDesc: "Find flights to your destination",
    afReservar: "See options",
    afTourCerca: "Book a tour nearby",
    afESIM: "International eSIM",
    afESIMDesc: "Data the moment you land via Airalo",
    afSeguro: "Travel insurance",
    afSeguroDesc: "Medical + cancellation cover",
    paywallTitulo: "Go Pro",
    paywallMotivoGuardar: "You're saving your second trip. With Pro you save unlimited trips, synced across devices.",
    paywallMotivoPDF: "Export your itinerary as PDF to take it offline.",
    paywallMotivoAlerta: "Get notified when the flight drops below a target price.",
    paywallMotivoGrafico: "See the full price history month by month.",
    paywallMotivoCompartir: "Share your plan with a public link.",
    paywallAnio: "year",
    paywallMes: "month",
    paywallUnaSolaVez: "one-time",
    paywallAhorroAnual: "Save 60% vs monthly",
    paywallLifetime100: "Launch offer · first 100",
    paywallV1: "Unlimited synced trips",
    paywallV2: "PDF export + sharing",
    paywallV3: "Unlimited price alerts",
    paywallV4: "Full history, no ads",
    paywallVAlt1: "All Pro features while active",
    paywallVAlt2: "Cancel anytime",
    paywallVLife1: "Lifetime Pro, no renewals",
    paywallEmpezar: "Start",
    paywallSinAtaduras: "Cancel anytime",
    paywallDevolucion: "14-day refund",
    paywallNecesitaLogin: "Sign in with your email first so we can link the purchase.",
    paywallNoConfigurado: "Checkout isn't configured yet.",
    alertaBoton: "Notify me if it drops",
    alertaModalEyebrow: "Price alert",
    alertaModalTitulo: "Watch {ciudad} for a price drop",
    alertaModalSub: "We email you the moment the detector spots a flight below your target.",
    alertaUmbral: "Email me if the price drops below:",
    alertaActualHoy: "Today:",
    alertaConfirmar: "Create alert",
    alertaCreada: "Alert activated!",
    alertaCreadaSub: "We'll email you as soon as the price drops.",
    alertaCerrar: "Close",
    alertaError: "Something failed. Try again.",
    alertaAuthTitulo: "We need your email for alerts",
    alertaAuthSub: "Sign in quickly and we'll link the alert to your account.",
    alertaEntrar: "Sign in",
    alertaPrivacidad: "Your email is used only for this alert. Cancel anytime.",
    menuUsuarioAria: "User menu",
    menuMisAlertas: "My alerts",
    menuSinAlertas: "No active alerts yet.",
    menuBorrarAlerta: "Delete",
    menuHazteProCTA: "Go Pro",
    menuGestionarPro: "Manage subscription",
    menuPlanes: "View plans",
    afNota: "Some links are affiliate links: if you book, we may earn a commission at no extra cost to you.",
    saludoManana: "Good morning",
    saludoTarde: "Good afternoon",
    saludoNoche: "Good evening",
    presupEyebrow: "Plan by budget",
    presupBoton: "Where can I travel on my budget?",
    presupTitulo: "Travel within your budget",
    presupSub: "See where you can go with what you have",
    presupTuPresup: "Your total budget",
    presupPersonas: "People",
    presupPersonaS: "person",
    presupPersonasP: "people",
    presupRegion: "Which region?",
    presupDestinos: "destinations within reach",
    presupVuelo: "Flight (round trip)",
    presupPrecioReal: "Live price",
    presupBuscarReal: "Check live price",
    presupBuscandoReal: "Fetching live prices…",
    presupNoEncontrado: "No live offer for this destination",
    presupVerAviasales: "Search on Aviasales",
    presupVerGoogle: "Search on Google",
    presupCompararGoogle: "Compare on Google Flights",
    presupEstimado: "Estimate",
    presupOfertaPara: "Deal for",
    presupHospedaje: "Accommodation",
    presupComida: "Food",
    presupTransporte: "Local transport",
    presupExtras: "Activities & extras",
    presupTeSobra: "You'd have left",
    presupTeFalta: "You're short",
    presupAlcanza: "enough for",
    presupPlanear: "Plan",
    presupVerVuelos: "Flights",
    presupAviso:
      "Average estimated costs for a mid-range tourist (USD). Flights are approximate from Colombia; confirm the real price with the flight detector.",
    heroEyebrow: "Plan your next adventure",
    destinosEyebrow: "Inspiration",
    recomendadoEyebrow: "We think you'll like",
    recomendadoTitulo: "Destinations for {nombre}",
    ideasEyebrow: "Quick ideas",
    ideaPresupuesto: "My budget",
    heroEyebrowBudget: "Plan your trip from {pais}",
    heroH1Budget: "How much can you spend?",
    heroSubBudget: "We tell you where to go, when it's cheaper, and build your day-by-day plan.",
    heroVerOpciones: "See options",
    heroOSabesDestino: "or if you already know where",
    descargarPDF: "Download as PDF",
    viajerosHoy: "travelers today",
    viajeroEnLinea: "traveler online",
    viajerosEnLinea: "travelers online",
    cargandoFase1: "Searching places near the center…",
    cargandoFase2: "Exploring up to 70 km around…",
    cargandoFase3: "Polishing photos and routes…",
    presupModoDestino: "One destination",
    presupModoRuta: "Multi-city route",
    presupRutaSub: "Build a multi-city route that fits your budget",
    presupDesdeCiudad: "Start the route at",
    presupSalesDesde: "Departing from",
    presupSalesDesdeNota: "Real prices scanned from these airports every 3 hours.",
    presupCoberturaTitulo: "Limited coverage",
    presupCoberturaAviso: "The detector doesn't scan prices from {pais} yet. We show orientative estimates; real prices are fetched live when you open a city.",
    presupAhorroDesde: "From {origen} you save",
    presupRutaTitulo: "Your recommended route",
    presupOtraRuta: "Another route",
    presupRutaCiudades: "cities",
    presupRutaDias: "days",
    presupNoRuta:
      "We couldn't find a route within your budget here. Raise the budget or days, or pick another region.",
    presupVueloIntl: "International flight (round trip)",
    presupEntreCiudades: "Inter-city transport",
    presupNoches: "nights",
    ofertasEyebrow: "Price alerts",
    ofertasTitulo: "Cheap flights from Colombia",
    ofertasSub: "Best fares detected from Bogotá and Medellín, refreshed every few hours.",
    ofertasTodos: "All",
    ofertasGanga: "Deal",
    ofertasIdaVuelta: "round trip",
    ofertasPlanear: "Plan",
    ofertasActualizado: "Updated",
    ofertasHaceMin: "seen {n} min ago",
    ofertasHaceHoras: "seen {n} h ago",
    ofertasActualizado: "Prices updated",
    ofertasHaceDias: "seen {n} d ago",
    ofertasAprox: "Approx. price",
    ofertasComparar: "Compare on Google",
    ofertasViajerosVieron: "travelers searched it",
    ofertasMisFechas: "Search my dates",
    fechaIda: "Departure",
    fechaVuelta: "Return",
    limpiar: "Clear",
    cuandoEyebrow: "Plan your dates",
    cuandoTitulo: "When do you want to travel?",
    guardarViaje: "Save",
    guardado: "Saved",
    misViajesEyebrow: "Your plans",
    misViajesTitulo: "My saved trips",
    misViajesReabrir: "Reopen",
    misViajesEliminar: "Delete",
    misViajesSync: "Synced",
    // Entry requirements
    reqTitulo: "Entry requirements for",
    reqTuPasaporte: "Your passport:",
    reqVisa: "Visa",
    reqVisaNota: "For tourism/short stays. Conditions may vary.",
    req_sinvisa: "Visa-free",
    req_sinvisaDias: "Visa-free · {n} days",
    req_llegada: "Visa on arrival",
    req_evisa: "Electronic visa (e-visa)",
    req_eta: "Travel authorization (ETA)",
    req_requerida: "Visa required (apply in advance)",
    req_noadmision: "Entry not allowed",
    req_mismopais: "This is your country",
    req_desconocido: "Check the requirements",
    reqPasaporte: "Passport",
    reqPasaporteNota: "Valid · 6+ months recommended",
    reqSalud: "Health",
    reqFiebreSi: "Yellow fever certificate may be required",
    reqFiebreNo: "No common mandatory vaccines",
    reqVerOficial: "See official requirements",
    reqVerSalud: "Vaccines & health",
    reqDatosPais: "Useful country info",
    reqMoneda: "Currency",
    reqIdioma: "Language",
    reqCapital: "Capital",
    reqHuso: "Time zone",
    reqConduccion: "Drives on the",
    reqTelefono: "Phone code",
    reqIzquierda: "Left",
    reqDerecha: "Right",
    reqEnchufe: "Power plug",
    reqEstaciones: "Seasons",
    estac_norte: "Summer Jun–Aug · Winter Dec–Feb",
    estac_sur: "Summer Dec–Feb · Winter Jun–Aug",
    estac_tropical: "Tropical (little variation)",
    reqAgua: "Tap water",
    reqPropina: "Tipping",
    agua_potable: "Drinkable",
    agua_precaucion: "Prefer bottled",
    agua_no: "Not drinkable",
    prop_no: "Not customary",
    prop_incluido: "Usually included",
    prop_diez: "~10% common",
    prop_veinte: "15–20% expected",
    reqDisclaimer: "Reference info only. Requirements change; always confirm with the embassy/consulate and official sources before booking or traveling.",
    reqFuente: "Source",
    ofertasFuente: "Reference prices",
    todosLugares: "All places",
    agregar: "Add",
    presupBuscarCiudad: "Search city or country…",
    presupExcluidas: "Excluded",
    presupExcluir: "Remove this city from the route",
    asesorBoton: "Travel advisor",
    asesorTitulo: "Compass · Travel advisor",
    asesorSubtitulo: "Your AI guide",
    asesorSaludo: "Hi{nombre}! I'm Compass 🧭, your travel advisor. Tell me your budget, dates or what you'd like to see and I'll put together options.",
    asesorPlaceholder: "Ask me where to travel…",
    asesorError: "I had a problem responding. Try again.",
    asesorSinClave: "The AI advisor isn't enabled yet. To turn it on, add your ANTHROPIC_API_KEY in Vercel (Settings → Environment Variables) and redeploy.",
    asesorModoGuia: "Free guide (no cost)",
    asesorTabGuia: "Guide",
    asesorTabIA: "AI",
    asesorAvisoIA: "AI mode: free chat with Claude. Uses API credits.",
    guiaSaludo: "Hi{nombre}! I'm your guide 🧭. I'll build you a route for free. First: which region do you want to travel to?",
    guiaPreguntaPresupuesto: "What's your total budget?",
    guiaPreguntaDias: "How many days do you have?",
    guiaAquiRuta: "This route fits 👇",
    guiaSinRuta: "With that I couldn't find a route within budget. Try raising the budget or days, or pick another region.",
    guiaVerPresupuesto: "See full budget",
    guiaReiniciar: "Start over",
    asesorEj1: "3 days in Lisbon?",
    asesorEj2: "Cheap beach in December?",
    asesorEj3: "What to do in Rome?",
    verMas: "See more",
    verMenos: "See less",
    ajustarViaje: "Adjust trip",
    compartir: "Share",
    copiado: "Copied!",
    miViajeA: "My trip to",
    hechoCon: "Made with",
  },

  pt: {
    tagline: "Seu roteiro perfeito em qualquer cidade do mundo",
    buscarPlaceholder: "Cidade, País (ex. Madri, Espanha)",
    buscar: "Buscar",
    heroTitulo: "Sua viagem, planejada em segundos",
    heroTexto:
      "Roteiro dia a dia com os melhores lugares, fotos, restaurantes e como se locomover. Tudo aqui, sem sair do app.",
    benDiaTitulo: "Dia a dia",
    benDiaTexto: "Distribui os lugares conforme seu tempo",
    benGpsTitulo: "GPS ao vivo",
    benGpsTexto: "Avisa se você está adiantado ou atrasado",
    benComerTitulo: "Comer e sair",
    benComerTexto: "Restaurantes, cafés e vida noturna",
    benLlegarTitulo: "Como chegar",
    benLlegarTexto: "Transporte, tempo e custo entre pontos",
    pruebaPopular: "Experimente um destino popular:",
    dias: "Dias",
    horasDia: "Horas/dia",
    recalcular: "Recalcular",
    diurno: "Diurno",
    nocturno: "Noturno",
    diurnoDesc: "Monumentos, museus e passeios",
    nocturnoDesc: "Bares, mirantes e vida noturna",
    lugares: "lugares",
    cat_imperdibles: "Imperdíveis",
    cat_restaurantes: "Restaurantes",
    cat_cafes: "Cafés",
    cat_bares: "Bares / Noite",
    cat_miradores: "Mirantes",
    cat_museos: "Museus",
    cat_monumentos: "Monumentos",
    cat_parques: "Parques",
    cat_estadios: "Estádios",
    dia: "Dia",
    paradas: "paradas",
    enTotal: "no total",
    visitas: "Visitas",
    traslados: "Deslocamentos",
    empezarGps: "Começar dia com rastreamento GPS",
    llegueSiguiente: "Cheguei no próximo",
    terminar: "Terminar",
    parada: "Parada",
    sinParadas:
      "Sem paradas para este dia com o tempo configurado. Aumente as horas por dia ou reduza o número de dias.",
    cargandoLugares: "Buscando os melhores lugares…",
    sinResultados:
      "Não encontramos lugares desta categoria perto do centro. Tente outra categoria ou toque em Recalcular.",
    cargando: "Carregando…",
    verFoto: "Ver foto e como chegar",
    cambiar: "Trocar",
    quitar: "Remover",
    comoLlegar: "Como chegar",
    desdeTuUbicacion: "da sua localização",
    activaGps:
      "Ative o GPS (abaixo no app) para ver o transporte e o tempo exatos de onde você está.",
    estasA: "Você está a",
    deAqui: "daqui. Escolha como chegar:",
    desdeCentro: "do centro de",
    verRuta: "Ver rota",
    recomendado: "recomendado",
    aproxAviso:
      "Tempos e custos aproximados. A rota é desenhada no mapa do app.",
    activarGps: "Ativar GPS para me ver no mapa e calcular tempos ao vivo",
    activo: "ativo",
    atrasado: "Você está {n} min atrasado",
    adelantado: "Você está {n} min adiantado",
    enHora: "Você está no horário",
    caminar: "Caminhar",
    metroBus: "Metrô / Ônibus",
    bici: "Bike",
    taxiApp: "Táxi / App",
    gratis: "Grátis",
    hola: "Olá",
    entrar: "Entrar",
    salir: "Sair",
    inicio: "Início",
    tuNombre: "Como você se chama?",
    comenzar: "Começar",
    entrarGoogle: "Continuar com o Google",
    oContinuar: "ou",
    authEntrarEmail: "Entrar com email",
    authTuEmail: "Seu email",
    authEnviarCodigo: "Enviar código",
    authVerificar: "Verificar e entrar",
    authVolver: "Voltar",
    authCambiarEmail: "Mudar email",
    authMandamosCodigo: "Enviamos um código de 6 dígitos para",
    authComoLlamamos: "Como você quer que te chamemos? (opcional)",
    authErrorEmail: "Verifique o formato do email.",
    authErrorEnvio: "Não conseguimos enviar o código. Tente novamente.",
    authErrorCodigo: "Digite os 6 dígitos do código.",
    authErrorCodigoMal: "Código incorreto ou expirado.",
    idioma: "Idioma",
    footer: "Dados do OpenStreetMap e Wikipedia",
    // Afiliados / reservas
    afTitulo: "Reserve sua viagem",
    afTours: "Tours e experiências",
    afToursDesc: "Atividades com guia perto da sua rota",
    afHoteles: "Onde ficar?",
    afHotelesDesc: "Hotéis perto do seu itinerário",
    afVuelos: "Voos",
    afVuelosDesc: "Encontre voos para o seu destino",
    afReservar: "Ver opções",
    afTourCerca: "Reserve um tour por perto",
    afESIM: "eSIM internacional",
    afESIMDesc: "Dados ao chegar com Airalo",
    afSeguro: "Seguro de viagem",
    afSeguroDesc: "Cobertura médica + cancelamento",
    paywallTitulo: "Vire Pro",
    paywallMotivoGuardar: "Você está salvando sua segunda viagem. Com o Pro você salva quantas quiser, sincronizadas em todos os dispositivos.",
    paywallMotivoPDF: "Exporte seu roteiro em PDF para usar offline.",
    paywallMotivoAlerta: "Receba um aviso quando o voo cair abaixo de um preço.",
    paywallMotivoGrafico: "Veja o histórico completo de preços mês a mês.",
    paywallMotivoCompartir: "Compartilhe seu plano com um link público.",
    paywallAnio: "ano",
    paywallMes: "mês",
    paywallUnaSolaVez: "única vez",
    paywallAhorroAnual: "Economize 60% vs mensal",
    paywallLifetime100: "Oferta de lançamento · primeiros 100",
    paywallV1: "Viagens ilimitadas sincronizadas",
    paywallV2: "Exportar PDF e compartilhar",
    paywallV3: "Alertas de preço ilimitados",
    paywallV4: "Histórico completo, sem anúncios",
    paywallVAlt1: "Tudo do Pro enquanto estiver ativo",
    paywallVAlt2: "Cancele quando quiser",
    paywallVLife1: "Pro vitalício, sem renovações",
    paywallEmpezar: "Começar",
    paywallSinAtaduras: "Cancele quando quiser",
    paywallDevolucion: "Devolução 14 dias",
    paywallNecesitaLogin: "Entre com seu email primeiro para associar a compra.",
    paywallNoConfigurado: "Checkout ainda não configurado.",
    alertaBoton: "Avise-me se cair",
    alertaModalEyebrow: "Alerta de preço",
    alertaModalTitulo: "Avise-me quando {ciudad} cair",
    alertaModalSub: "Enviamos um email assim que detectarmos um voo abaixo do seu alvo.",
    alertaUmbral: "Avise-me se o preço cair abaixo de:",
    alertaActualHoy: "Hoje:",
    alertaConfirmar: "Criar alerta",
    alertaCreada: "Alerta ativado!",
    alertaCreadaSub: "Avisamos por email assim que o preço cair.",
    alertaCerrar: "Fechar",
    alertaError: "Algo falhou. Tente novamente.",
    alertaAuthTitulo: "Precisamos do seu email para alertas",
    alertaAuthSub: "Entre rapidamente e vinculamos o alerta à sua conta.",
    alertaEntrar: "Entrar",
    alertaPrivacidad: "Seu email é usado só para este alerta. Cancele quando quiser.",
    menuUsuarioAria: "Menu do usuário",
    menuMisAlertas: "Meus alertas",
    menuSinAlertas: "Ainda sem alertas ativos.",
    menuBorrarAlerta: "Excluir",
    menuHazteProCTA: "Vire Pro",
    menuGestionarPro: "Gerenciar assinatura",
    menuPlanes: "Ver planos",
    afNota: "Alguns links são de afiliados: se você reservar, podemos ganhar uma comissão sem custo extra para você.",
    saludoManana: "Bom dia",
    saludoTarde: "Boa tarde",
    saludoNoche: "Boa noite",
    presupEyebrow: "Planeje por orçamento",
    presupBoton: "Para onde viajar com meu orçamento?",
    presupTitulo: "Viaje com seu orçamento",
    presupSub: "Veja aonde você pode ir com o que tem",
    presupTuPresup: "Seu orçamento total",
    presupPersonas: "Pessoas",
    presupPersonaS: "pessoa",
    presupPersonasP: "pessoas",
    presupRegion: "Qual região?",
    presupDestinos: "destinos ao seu alcance",
    presupVuelo: "Voo (ida e volta)",
    presupPrecioReal: "Preço real",
    presupBuscarReal: "Ver preço ao vivo",
    presupBuscandoReal: "Buscando preços ao vivo…",
    presupNoEncontrado: "Sem oferta ao vivo para este destino",
    presupVerAviasales: "Buscar no Aviasales",
    presupVerGoogle: "Buscar no Google",
    presupCompararGoogle: "Comparar no Google Voos",
    presupEstimado: "Estimado",
    presupOfertaPara: "Oferta para",
    presupHospedaje: "Hospedagem",
    presupComida: "Comida",
    presupTransporte: "Transporte local",
    presupExtras: "Atividades e extras",
    presupTeSobra: "Sobraria",
    presupTeFalta: "Faltam",
    presupAlcanza: "dá para",
    presupPlanear: "Planejar",
    presupVerVuelos: "Voos",
    presupAviso:
      "Custos médios estimados para um turista intermediário (USD). Os voos são aproximados desde a Colômbia; confirme o preço real com o detector de voos.",
    heroEyebrow: "Planeje sua próxima aventura",
    destinosEyebrow: "Inspiração",
    recomendadoEyebrow: "Achamos que você vai gostar",
    recomendadoTitulo: "Destinos para {nombre}",
    ideasEyebrow: "Ideias para começar",
    ideaPresupuesto: "Meu orçamento",
    heroEyebrowBudget: "Planeje sua viagem desde {pais}",
    heroH1Budget: "Quanto tem para gastar?",
    heroSubBudget: "Te dizemos para onde ir, quando é mais barato e montamos o plano dia a dia.",
    heroVerOpciones: "Ver opções",
    heroOSabesDestino: "ou se já sabe para onde",
    descargarPDF: "Baixar como PDF",
    viajerosHoy: "viajantes hoje",
    viajeroEnLinea: "viajante online",
    viajerosEnLinea: "viajantes online",
    cargandoFase1: "Buscando lugares perto do centro…",
    cargandoFase2: "Explorando até 70 km ao redor…",
    cargandoFase3: "Polindo fotos e rotas…",
    presupModoDestino: "Um destino",
    presupModoRuta: "Rota multicidades",
    presupRutaSub: "Monte uma rota de várias cidades que caiba no seu orçamento",
    presupDesdeCiudad: "Começar a rota por",
    presupSalesDesde: "Saindo de",
    presupSalesDesdeNota: "Preços reais escaneados destes aeroportos a cada 3 horas.",
    presupCoberturaTitulo: "Cobertura limitada",
    presupCoberturaAviso: "O detector ainda não escaneia preços desde {pais}. Mostramos estimativas; preços reais são buscados ao vivo ao abrir uma cidade.",
    presupAhorroDesde: "De {origen} você economiza",
    presupRutaTitulo: "Sua rota recomendada",
    presupOtraRuta: "Outra rota",
    presupRutaCiudades: "cidades",
    presupRutaDias: "dias",
    presupNoRuta:
      "Não encontramos uma rota dentro do seu orçamento aqui. Aumente o orçamento ou os dias, ou escolha outra região.",
    presupVueloIntl: "Voo internacional (ida e volta)",
    presupEntreCiudades: "Transporte entre cidades",
    presupNoches: "noites",
    ofertasEyebrow: "Alertas de preço",
    ofertasTitulo: "Voos baratos da Colômbia",
    ofertasSub: "Melhores preços detectados de Bogotá e Medellín, atualizados a cada poucas horas.",
    ofertasTodos: "Todos",
    ofertasGanga: "Oferta",
    ofertasIdaVuelta: "ida e volta",
    ofertasPlanear: "Planejar",
    ofertasActualizado: "Atualizado",
    ofertasHaceMin: "visto há {n} min",
    ofertasHaceHoras: "visto há {n} h",
    ofertasActualizado: "Preços atualizados",
    ofertasHaceDias: "visto há {n} d",
    ofertasAprox: "Preço aproximado",
    ofertasViajerosVieron: "viajantes buscaram",
    ofertasComparar: "Comparar no Google",
    ofertasMisFechas: "Buscar nas minhas datas",
    fechaIda: "Ida",
    fechaVuelta: "Volta",
    limpiar: "Limpar",
    cuandoEyebrow: "Planeje suas datas",
    cuandoTitulo: "Quando você quer viajar?",
    guardarViaje: "Salvar",
    guardado: "Salvo",
    misViajesEyebrow: "Seus planos",
    misViajesTitulo: "Minhas viagens salvas",
    misViajesReabrir: "Reabrir",
    misViajesEliminar: "Excluir",
    misViajesSync: "Sincronizado",
    // Requisitos de entrada
    reqTitulo: "Requisitos de entrada para",
    reqTuPasaporte: "Seu passaporte:",
    reqVisa: "Visto",
    reqVisaNota: "Para turismo/estadias curtas. As condições podem variar.",
    req_sinvisa: "Sem visto",
    req_sinvisaDias: "Sem visto · {n} dias",
    req_llegada: "Visto na chegada",
    req_evisa: "Visto eletrônico (e-visa)",
    req_eta: "Autorização eletrônica (ETA)",
    req_requerida: "Visto obrigatório (solicite antes)",
    req_noadmision: "Entrada não permitida",
    req_mismopais: "É o seu país",
    req_desconocido: "Consulte os requisitos",
    reqPasaporte: "Passaporte",
    reqPasaporteNota: "Válido · mín. 6 meses recomendado",
    reqSalud: "Saúde",
    reqFiebreSi: "Pode ser exigido certificado de febre amarela",
    reqFiebreNo: "Sem vacinas obrigatórias frequentes",
    reqVerOficial: "Ver requisitos oficiais",
    reqVerSalud: "Vacinas e saúde",
    reqDatosPais: "Dados úteis do país",
    reqMoneda: "Moeda",
    reqIdioma: "Idioma",
    reqCapital: "Capital",
    reqHuso: "Fuso horário",
    reqConduccion: "Conduz-se pela",
    reqTelefono: "Código tel.",
    reqIzquierda: "Esquerda",
    reqDerecha: "Direita",
    reqEnchufe: "Tomada",
    reqEstaciones: "Estações",
    estac_norte: "Verão jun–ago · Inverno dez–fev",
    estac_sur: "Verão dez–fev · Inverno jun–ago",
    estac_tropical: "Tropical (pouca variação)",
    reqAgua: "Água da torneira",
    reqPropina: "Gorjeta",
    agua_potable: "Potável",
    agua_precaucion: "Prefira engarrafada",
    agua_no: "Não potável",
    prop_no: "Não se costuma",
    prop_incluido: "Geralmente incluída",
    prop_diez: "~10% comum",
    prop_veinte: "15–20% esperada",
    reqDisclaimer: "Informação referencial. Os requisitos mudam; confirme sempre com a embaixada/consulado e fontes oficiais antes de comprar ou viajar.",
    reqFuente: "Fonte",
    ofertasFuente: "Preços de referência",
    todosLugares: "Todos os lugares",
    agregar: "Adicionar",
    presupBuscarCiudad: "Buscar cidade ou país…",
    presupExcluidas: "Excluídas",
    presupExcluir: "Remover esta cidade da rota",
    asesorBoton: "Consultor de viagens",
    asesorTitulo: "Bússola · Consultor de viagens",
    asesorSubtitulo: "Seu guia com IA",
    asesorSaludo: "Olá{nombre}! Sou a Bússola 🧭, sua consultora de viagens. Conte seu orçamento, datas ou o que gostaria de conhecer e eu monto opções.",
    asesorPlaceholder: "Pergunte para onde viajar…",
    asesorError: "Tive um problema para responder. Tente de novo.",
    asesorSinClave: "O consultor com IA ainda não está ativado. Para ligá-lo, adicione sua ANTHROPIC_API_KEY no Vercel (Settings → Environment Variables) e publique de novo.",
    asesorModoGuia: "Guia grátis (sem custo)",
    asesorTabGuia: "Guia",
    asesorTabIA: "IA",
    asesorAvisoIA: "Modo IA: conversa livre com Claude. Consome créditos da API.",
    guiaSaludo: "Olá{nombre}! Sou seu guia 🧭. Monto uma rota sem custo. Primeiro: para qual região quer viajar?",
    guiaPreguntaPresupuesto: "Qual é seu orçamento total?",
    guiaPreguntaDias: "Quantos dias você tem?",
    guiaAquiRuta: "Esta rota cabe 👇",
    guiaSinRuta: "Com isso não encontrei uma rota dentro do orçamento. Tente aumentar o orçamento ou os dias, ou escolha outra região.",
    guiaVerPresupuesto: "Ver orçamento completo",
    guiaReiniciar: "Começar de novo",
    asesorEj1: "3 dias em Lisboa?",
    asesorEj2: "Praia barata em dezembro?",
    asesorEj3: "O que fazer em Roma?",
    verMas: "Ver mais",
    verMenos: "Ver menos",
    ajustarViaje: "Ajustar viagem",
    compartir: "Compartilhar",
    copiado: "Copiado!",
    miViajeA: "Minha viagem a",
    hechoCon: "Feito com",
  },

  fr: {
    tagline: "Votre itinéraire parfait dans n'importe quelle ville du monde",
    buscarPlaceholder: "Ville, Pays (ex. Madrid, Espagne)",
    buscar: "Rechercher",
    heroTitulo: "Votre voyage, planifié en quelques secondes",
    heroTexto:
      "Itinéraire jour par jour avec les meilleurs lieux, photos, restaurants et comment se déplacer. Tout ici, sans quitter l'app.",
    benDiaTitulo: "Jour par jour",
    benDiaTexto: "Répartit les lieux selon votre temps",
    benGpsTitulo: "GPS en direct",
    benGpsTexto: "Vous dit si vous êtes en avance ou en retard",
    benComerTitulo: "Manger et sortir",
    benComerTexto: "Restaurants, cafés et vie nocturne",
    benLlegarTitulo: "Comment y aller",
    benLlegarTexto: "Transport, temps et coût entre les points",
    pruebaPopular: "Essayez une destination populaire :",
    dias: "Jours",
    horasDia: "Heures/jour",
    recalcular: "Recalculer",
    diurno: "Jour",
    nocturno: "Nuit",
    diurnoDesc: "Monuments, musées et balades",
    nocturnoDesc: "Bars, points de vue et vie nocturne",
    lugares: "lieux",
    cat_imperdibles: "Incontournables",
    cat_restaurantes: "Restaurants",
    cat_cafes: "Cafés",
    cat_bares: "Bars / Nuit",
    cat_miradores: "Points de vue",
    cat_museos: "Musées",
    cat_monumentos: "Monuments",
    cat_parques: "Parcs",
    cat_estadios: "Stades",
    dia: "Jour",
    paradas: "arrêts",
    enTotal: "au total",
    visitas: "Visites",
    traslados: "Trajets",
    empezarGps: "Commencer la journée avec suivi GPS",
    llegueSiguiente: "Je suis arrivé au suivant",
    terminar: "Terminer",
    parada: "Arrêt",
    sinParadas:
      "Aucun arrêt pour cette journée avec le temps configuré. Augmentez les heures par jour ou réduisez le nombre de jours.",
    cargandoLugares: "Recherche des meilleurs lieux…",
    sinResultados:
      "Aucun lieu de cette catégorie près du centre. Essayez une autre catégorie ou appuyez sur Recalculer.",
    cargando: "Chargement…",
    verFoto: "Voir la photo et l'itinéraire",
    cambiar: "Changer",
    quitar: "Retirer",
    comoLlegar: "Comment y aller",
    desdeTuUbicacion: "depuis votre position",
    activaGps:
      "Activez le GPS (en bas de l'app) pour voir le transport et le temps exacts depuis votre position.",
    estasA: "Vous êtes à",
    deAqui: "d'ici. Choisissez comment y aller :",
    desdeCentro: "du centre de",
    verRuta: "Voir l'itinéraire",
    recomendado: "recommandé",
    aproxAviso:
      "Temps et coûts approximatifs. L'itinéraire est tracé sur la carte de l'app.",
    activarGps:
      "Activer le GPS pour me voir sur la carte et calculer les temps en direct",
    activo: "actif",
    atrasado: "Vous avez {n} min de retard",
    adelantado: "Vous avez {n} min d'avance",
    enHora: "Vous êtes à l'heure",
    caminar: "Marcher",
    metroBus: "Métro / Bus",
    bici: "Vélo",
    taxiApp: "Taxi / App",
    gratis: "Gratuit",
    hola: "Bonjour",
    entrar: "Se connecter",
    salir: "Se déconnecter",
    inicio: "Accueil",
    tuNombre: "Comment vous appelez-vous ?",
    comenzar: "Commencer",
    entrarGoogle: "Continuer avec Google",
    oContinuar: "ou",
    authEntrarEmail: "Se connecter par email",
    authTuEmail: "Votre email",
    authEnviarCodigo: "Envoyer le code",
    authVerificar: "Vérifier et entrer",
    authVolver: "Retour",
    authCambiarEmail: "Changer l'email",
    authMandamosCodigo: "Nous avons envoyé un code à 6 chiffres à",
    authComoLlamamos: "Comment voulez-vous qu'on vous appelle ? (optionnel)",
    authErrorEmail: "Vérifiez le format de l'email.",
    authErrorEnvio: "Impossible d'envoyer le code. Réessayez.",
    authErrorCodigo: "Saisissez les 6 chiffres du code.",
    authErrorCodigoMal: "Code incorrect ou expiré.",
    idioma: "Langue",
    footer: "Données d'OpenStreetMap et Wikipedia",
    // Afiliados / reservas
    afTitulo: "Réservez votre voyage",
    afTours: "Visites et activités",
    afToursDesc: "Activités guidées près de votre itinéraire",
    afHoteles: "Où dormir ?",
    afHotelesDesc: "Hôtels près de votre itinéraire",
    afVuelos: "Vols",
    afVuelosDesc: "Trouvez des vols vers votre destination",
    afReservar: "Voir les options",
    afTourCerca: "Réservez une visite à proximité",
    afESIM: "eSIM internationale",
    afESIMDesc: "Data dès l'arrivée avec Airalo",
    afSeguro: "Assurance voyage",
    afSeguroDesc: "Couverture médicale + annulation",
    paywallTitulo: "Passez à Pro",
    paywallMotivoGuardar: "Vous enregistrez votre deuxième voyage. Avec Pro vous en sauvegardez autant que voulu, synchronisés.",
    paywallMotivoPDF: "Exportez votre itinéraire en PDF hors ligne.",
    paywallMotivoAlerta: "Recevez une alerte quand le vol baisse sous un certain prix.",
    paywallMotivoGrafico: "Voyez l'historique complet des prix mois par mois.",
    paywallMotivoCompartir: "Partagez votre plan avec un lien public.",
    paywallAnio: "an",
    paywallMes: "mois",
    paywallUnaSolaVez: "une seule fois",
    paywallAhorroAnual: "Économisez 60% vs mensuel",
    paywallLifetime100: "Offre de lancement · 100 premiers",
    paywallV1: "Voyages illimités synchronisés",
    paywallV2: "Export PDF et partage",
    paywallV3: "Alertes de prix illimitées",
    paywallV4: "Historique complet, sans pubs",
    paywallVAlt1: "Toutes les fonctions Pro tant que c'est actif",
    paywallVAlt2: "Annulez quand vous voulez",
    paywallVLife1: "Pro à vie, sans renouvellements",
    paywallEmpezar: "Commencer",
    paywallSinAtaduras: "Annulez quand vous voulez",
    paywallDevolucion: "Remboursement 14 jours",
    paywallNecesitaLogin: "Connectez-vous par email d'abord pour associer l'achat.",
    paywallNoConfigurado: "Le paiement n'est pas encore configuré.",
    alertaBoton: "Préviens-moi si ça baisse",
    alertaModalEyebrow: "Alerte prix",
    alertaModalTitulo: "Préviens-moi quand {ciudad} baisse",
    alertaModalSub: "Email dès que le détecteur trouve un vol sous votre cible.",
    alertaUmbral: "Préviens-moi si le prix passe sous :",
    alertaActualHoy: "Aujourd'hui :",
    alertaConfirmar: "Créer l'alerte",
    alertaCreada: "Alerte activée !",
    alertaCreadaSub: "Email dès que le prix descend.",
    alertaCerrar: "Fermer",
    alertaError: "Quelque chose a échoué. Réessayez.",
    alertaAuthTitulo: "Email requis pour les alertes",
    alertaAuthSub: "Connectez-vous et on lie l'alerte à votre compte.",
    alertaEntrar: "Se connecter",
    alertaPrivacidad: "Email utilisé uniquement pour cette alerte. Annulez quand vous voulez.",
    menuUsuarioAria: "Menu utilisateur",
    menuMisAlertas: "Mes alertes",
    menuSinAlertas: "Aucune alerte active.",
    menuBorrarAlerta: "Supprimer",
    menuHazteProCTA: "Passez à Pro",
    menuGestionarPro: "Gérer l'abonnement",
    menuPlanes: "Voir les plans",
    afNota: "Certains liens sont des liens d'affiliation : si vous réservez, nous pouvons percevoir une commission sans coût supplémentaire pour vous.",
    saludoManana: "Bonjour",
    saludoTarde: "Bon après-midi",
    saludoNoche: "Bonsoir",
    presupEyebrow: "Planifier par budget",
    presupBoton: "Où voyager avec mon budget ?",
    presupTitulo: "Voyagez selon votre budget",
    presupSub: "Voyez où vous pouvez aller avec ce que vous avez",
    presupTuPresup: "Votre budget total",
    presupPersonas: "Personnes",
    presupPersonaS: "personne",
    presupPersonasP: "personnes",
    presupRegion: "Quelle région ?",
    presupDestinos: "destinations accessibles",
    presupVuelo: "Vol (aller-retour)",
    presupPrecioReal: "Prix réel",
    presupBuscarReal: "Voir le prix réel",
    presupBuscandoReal: "Recherche des prix réels…",
    presupNoEncontrado: "Pas d'offre réelle pour cette destination",
    presupVerAviasales: "Rechercher sur Aviasales",
    presupVerGoogle: "Rechercher sur Google",
    presupCompararGoogle: "Comparer sur Google Flights",
    presupEstimado: "Estimation",
    presupOfertaPara: "Offre pour",
    presupHospedaje: "Hébergement",
    presupComida: "Nourriture",
    presupTransporte: "Transport local",
    presupExtras: "Activités et extras",
    presupTeSobra: "Il vous resterait",
    presupTeFalta: "Il vous manque",
    presupAlcanza: "assez pour",
    presupPlanear: "Planifier",
    presupVerVuelos: "Vols",
    presupAviso:
      "Coûts moyens estimés pour un touriste de gamme moyenne (USD). Les vols sont approximatifs depuis la Colombie ; confirmez le prix réel avec le détecteur de vols.",
    heroEyebrow: "Planifiez votre prochaine aventure",
    destinosEyebrow: "Inspiration",
    recomendadoEyebrow: "Nous pensons que vous aimerez",
    recomendadoTitulo: "Destinations pour {nombre}",
    ideasEyebrow: "Idées pour démarrer",
    ideaPresupuesto: "Mon budget",
    heroEyebrowBudget: "Planifiez votre voyage depuis {pais}",
    heroH1Budget: "Combien pouvez-vous dépenser ?",
    heroSubBudget: "Nous vous disons où aller, quand c'est moins cher et planifions chaque jour.",
    heroVerOpciones: "Voir les options",
    heroOSabesDestino: "ou si vous savez déjà où",
    descargarPDF: "Télécharger en PDF",
    viajerosHoy: "voyageurs aujourd'hui",
    viajeroEnLinea: "voyageur en ligne",
    viajerosEnLinea: "voyageurs en ligne",
    cargandoFase1: "Recherche de lieux près du centre…",
    cargandoFase2: "Exploration jusqu'à 70 km autour…",
    cargandoFase3: "Polissage des photos et itinéraires…",
    presupModoDestino: "Une destination",
    presupModoRuta: "Itinéraire multi-villes",
    presupRutaSub: "Composez un itinéraire de plusieurs villes selon votre budget",
    presupDesdeCiudad: "Commencer l'itinéraire à",
    presupSalesDesde: "Au départ de",
    presupSalesDesdeNota: "Prix réels scannés depuis ces aéroports toutes les 3 heures.",
    presupCoberturaTitulo: "Couverture limitée",
    presupCoberturaAviso: "Le détecteur ne scanne pas encore les prix depuis {pais}. Nous affichons des estimations ; les prix réels sont récupérés en direct.",
    presupAhorroDesde: "Depuis {origen} vous économisez",
    presupRutaTitulo: "Votre itinéraire recommandé",
    presupOtraRuta: "Autre itinéraire",
    presupRutaCiudades: "villes",
    presupRutaDias: "jours",
    presupNoRuta:
      "Aucun itinéraire dans votre budget ici. Augmentez le budget ou les jours, ou choisissez une autre région.",
    presupVueloIntl: "Vol international (aller-retour)",
    presupEntreCiudades: "Transport entre villes",
    presupNoches: "nuits",
    ofertasEyebrow: "Alertes de prix",
    ofertasTitulo: "Vols pas chers depuis la Colombie",
    ofertasSub: "Meilleurs prix détectés depuis Bogotá et Medellín, actualisés toutes les quelques heures.",
    ofertasTodos: "Tous",
    ofertasGanga: "Offre",
    ofertasIdaVuelta: "aller-retour",
    ofertasPlanear: "Planifier",
    ofertasActualizado: "Mis à jour",
    ofertasHaceMin: "vu il y a {n} min",
    ofertasHaceHoras: "vu il y a {n} h",
    ofertasActualizado: "Prix mis à jour",
    ofertasHaceDias: "vu il y a {n} j",
    ofertasAprox: "Prix approximatif",
    ofertasViajerosVieron: "voyageurs ont recherché",
    ofertasComparar: "Comparer sur Google",
    ofertasMisFechas: "Chercher à mes dates",
    fechaIda: "Aller",
    fechaVuelta: "Retour",
    limpiar: "Effacer",
    cuandoEyebrow: "Planifiez vos dates",
    cuandoTitulo: "Quand voulez-vous voyager ?",
    guardarViaje: "Enregistrer",
    guardado: "Enregistré",
    misViajesEyebrow: "Vos plans",
    misViajesTitulo: "Mes voyages enregistrés",
    misViajesReabrir: "Rouvrir",
    misViajesEliminar: "Supprimer",
    misViajesSync: "Synchronisé",
    // Formalités d'entrée
    reqTitulo: "Formalités d'entrée pour",
    reqTuPasaporte: "Votre passeport :",
    reqVisa: "Visa",
    reqVisaNota: "Pour tourisme/courts séjours. Les conditions peuvent varier.",
    req_sinvisa: "Sans visa",
    req_sinvisaDias: "Sans visa · {n} jours",
    req_llegada: "Visa à l'arrivée",
    req_evisa: "Visa électronique (e-visa)",
    req_eta: "Autorisation électronique (ETA)",
    req_requerida: "Visa requis (à demander avant)",
    req_noadmision: "Entrée non autorisée",
    req_mismopais: "C'est votre pays",
    req_desconocido: "Vérifiez les formalités",
    reqPasaporte: "Passeport",
    reqPasaporteNota: "Valide · 6 mois min. recommandé",
    reqSalud: "Santé",
    reqFiebreSi: "Certificat de fièvre jaune possiblement exigé",
    reqFiebreNo: "Pas de vaccins obligatoires fréquents",
    reqVerOficial: "Voir les formalités officielles",
    reqVerSalud: "Vaccins et santé",
    reqDatosPais: "Infos utiles du pays",
    reqMoneda: "Monnaie",
    reqIdioma: "Langue",
    reqCapital: "Capitale",
    reqHuso: "Fuseau horaire",
    reqConduccion: "On roule à",
    reqTelefono: "Indicatif tél.",
    reqIzquierda: "Gauche",
    reqDerecha: "Droite",
    reqEnchufe: "Prise",
    reqEstaciones: "Saisons",
    estac_norte: "Été juin–août · Hiver déc–févr",
    estac_sur: "Été déc–févr · Hiver juin–août",
    estac_tropical: "Tropical (peu de variation)",
    reqAgua: "Eau du robinet",
    reqPropina: "Pourboire",
    agua_potable: "Potable",
    agua_precaucion: "Préférez en bouteille",
    agua_no: "Non potable",
    prop_no: "Pas d'usage",
    prop_incluido: "Souvent inclus",
    prop_diez: "~10% courant",
    prop_veinte: "15–20% attendu",
    reqDisclaimer: "Information indicative. Les formalités changent ; confirmez toujours auprès de l'ambassade/consulat et des sources officielles avant de réserver ou voyager.",
    reqFuente: "Source",
    ofertasFuente: "Prix de référence",
    todosLugares: "Tous les lieux",
    agregar: "Ajouter",
    presupBuscarCiudad: "Rechercher ville ou pays…",
    presupExcluidas: "Exclues",
    presupExcluir: "Retirer cette ville de l'itinéraire",
    asesorBoton: "Conseiller voyage",
    asesorTitulo: "Boussole · Conseiller voyage",
    asesorSubtitulo: "Votre guide IA",
    asesorSaludo: "Bonjour{nombre} ! Je suis Boussole 🧭, votre conseillère voyage. Dites-moi votre budget, vos dates ou ce que vous aimeriez découvrir et je vous prépare des options.",
    asesorPlaceholder: "Demandez-moi où voyager…",
    asesorError: "J'ai eu un problème pour répondre. Réessayez.",
    asesorSinClave: "Le conseiller IA n'est pas encore activé. Pour l'activer, ajoutez votre ANTHROPIC_API_KEY dans Vercel (Settings → Environment Variables) et redéployez.",
    asesorModoGuia: "Guide gratuit (sans coût)",
    asesorTabGuia: "Guide",
    asesorTabIA: "IA",
    asesorAvisoIA: "Mode IA : conversation libre avec Claude. Consomme des crédits API.",
    guiaSaludo: "Bonjour{nombre} ! Je suis ton guide 🧭. Je te prépare un itinéraire gratuit. D'abord : vers quelle région veux-tu voyager ?",
    guiaPreguntaPresupuesto: "Quel est ton budget total ?",
    guiaPreguntaDias: "Combien de jours as-tu ?",
    guiaAquiRuta: "Cet itinéraire rentre 👇",
    guiaSinRuta: "Avec ça je n'ai pas trouvé d'itinéraire dans le budget. Augmente le budget ou les jours, ou choisis une autre région.",
    guiaVerPresupuesto: "Voir le budget complet",
    guiaReiniciar: "Recommencer",
    asesorEj1: "3 jours à Lisbonne ?",
    asesorEj2: "Plage pas chère en décembre ?",
    asesorEj3: "Que faire à Rome ?",
    verMas: "Voir plus",
    verMenos: "Voir moins",
    ajustarViaje: "Ajuster le voyage",
    compartir: "Partager",
    copiado: "Copié !",
    miViajeA: "Mon voyage à",
    hechoCon: "Fait avec",
  },
};

// Idioma por defecto según el navegador del usuario.
export function idiomaInicial() {
  if (typeof window === "undefined") return "es";
  const guardado = localStorage.getItem("idioma");
  if (guardado && T[guardado]) return guardado;
  const nav = (navigator.language || "es").slice(0, 2);
  return T[nav] ? nav : "es";
}

// Devuelve la función traductora t() para un idioma dado.
export function traductor(lang) {
  const dicc = T[lang] || T.es;
  return (clave, vars) => {
    let txt = dicc[clave] ?? T.es[clave] ?? clave;
    if (vars) for (const k in vars) txt = txt.replace(`{${k}}`, vars[k]);
    return txt;
  };
}
