// Sistema de traducción (i18n) de toda la app.
// Para añadir un idioma: copia un bloque y traduce los textos.
// Para añadir un texto: agrégalo con su clave en TODOS los idiomas.

export const IDIOMAS = {
  es: { nombre: "Español", bandera: "🇪🇸" },
  en: { nombre: "English", bandera: "🇬🇧" },
  pt: { nombre: "Português", bandera: "🇧🇷" },
  fr: { nombre: "Français", bandera: "🇫🇷" },
};

const T = {
  es: {
    // Cabecera y búsqueda
    tagline: "Tu itinerario perfecto en cualquier ciudad del mundo",
    buscarPlaceholder: "Ciudad, País (ej. Madrid, España)",
    buscar: "Buscar",
    // Inicio
    heroTitulo: "Tu viaje, planeado en segundos",
    heroTexto:
      "Itinerario día a día con los mejores lugares, fotos, restaurantes y cómo moverte entre ellos. Todo aquí, sin salir de la app.",
    benDiaTitulo: "Día por día",
    benDiaTexto: "Reparte los lugares según tu tiempo",
    benGpsTitulo: "GPS en vivo",
    benGpsTexto: "Te avisa si vas adelantado o atrasado",
    benComerTitulo: "Comer y salir",
    benComerTexto: "Restaurantes, cafés y vida nocturna",
    benLlegarTitulo: "Cómo llegar",
    benLlegarTexto: "Transporte, tiempo y costo entre puntos",
    pruebaPopular: "Prueba con un destino popular:",
    // Configuración
    dias: "Días",
    horasDia: "Horas/día",
    recalcular: "Recalcular",
    diurno: "Diurno",
    nocturno: "Nocturno",
    diurnoDesc: "Monumentos, museos y paseos",
    nocturnoDesc: "Bares, miradores y vida nocturna",
    lugares: "lugares",
    // Categorías
    cat_imperdibles: "Imperdibles",
    cat_restaurantes: "Restaurantes",
    cat_cafes: "Cafés",
    cat_bares: "Bares / Noche",
    cat_miradores: "Miradores",
    cat_museos: "Museos",
    cat_monumentos: "Monumentos",
    cat_parques: "Parques",
    cat_estadios: "Estadios",
    // Itinerario
    dia: "Día",
    paradas: "paradas",
    enTotal: "en total",
    visitas: "Visitas",
    traslados: "Traslados",
    empezarGps: "Empezar día con seguimiento GPS",
    llegueSiguiente: "Llegué a la siguiente",
    terminar: "Terminar",
    parada: "Parada",
    sinParadas:
      "No hay paradas para este día con el tiempo configurado. Sube las horas por día o reduce el número de días.",
    cargandoLugares: "Buscando los mejores lugares…",
    sinResultados:
      "No encontramos lugares de esta categoría cerca del centro. Prueba otra categoría o toca Recalcular.",
    cargando: "Cargando…",
    // Acciones de parada
    verFoto: "Ver foto y cómo llegar",
    cambiar: "Cambiar",
    quitar: "Quitar",
    // Detalle del lugar
    comoLlegar: "Cómo llegar",
    desdeTuUbicacion: "desde tu ubicación",
    activaGps:
      "Activa el GPS (abajo en la app) para ver el transporte y el tiempo exactos desde donde estás.",
    estasA: "Estás a",
    deAqui: "de aquí. Elige cómo llegar:",
    desdeCentro: "del centro de",
    verRuta: "Ver ruta",
    recomendado: "recomendado",
    aproxAviso:
      "Tiempos y costos aproximados. La ruta se dibuja en el mapa de la app.",
    // GPS
    activarGps: "Activar GPS para verme en el mapa y calcular tiempos en vivo",
    activo: "activo",
    // Estado de tiempo
    atrasado: "Vas {n} min atrasado",
    adelantado: "Vas {n} min adelantado",
    enHora: "Vas en hora",
    // Transporte
    caminar: "Caminar",
    metroBus: "Metro / Bus",
    bici: "Bici",
    taxiApp: "Taxi / App",
    gratis: "Gratis",
    // Login / perfil
    hola: "Hola",
    entrar: "Entrar",
    salir: "Salir",
    inicio: "Inicio",
    tuNombre: "¿Cómo te llamas?",
    comenzar: "Comenzar",
    idioma: "Idioma",
    footer: "Datos de OpenStreetMap y Wikipedia",
    // Afiliados / reservas
    afTitulo: "Reserva tu viaje",
    afTours: "Tours y experiencias",
    afToursDesc: "Actividades con guía cerca de tu ruta",
    afHoteles: "¿Dónde dormir?",
    afHotelesDesc: "Hoteles cerca de tu itinerario",
    afVuelos: "Vuelos",
    afVuelosDesc: "Encuentra vuelos a tu destino",
    afReservar: "Ver opciones",
    afTourCerca: "Reserva un tour aquí cerca",
    afNota: "Algunos enlaces son de afiliados: si reservas, podemos ganar una comisión sin costo extra para ti.",
    saludoManana: "Buenos días",
    saludoTarde: "Buenas tardes",
    saludoNoche: "Buenas noches",
    // Presupuesto
    presupEyebrow: "Planifica por presupuesto",
    presupBoton: "¿Adónde viajar con mi presupuesto?",
    presupTitulo: "Viaja con tu presupuesto",
    presupSub: "Mira a dónde puedes ir con lo que tienes",
    presupTuPresup: "Tu presupuesto total",
    presupPersonas: "Personas",
    presupPersonaS: "persona",
    presupPersonasP: "personas",
    presupRegion: "¿A qué región?",
    presupDestinos: "destinos a tu alcance",
    presupVuelo: "Vuelo (ida y vuelta)",
    presupHospedaje: "Hospedaje",
    presupComida: "Comida",
    presupTransporte: "Transporte local",
    presupExtras: "Actividades y extras",
    presupTeSobra: "Te sobra",
    presupTeFalta: "Te falta",
    presupAlcanza: "alcanza para",
    presupPlanear: "Planear",
    presupVerVuelos: "Ver vuelos",
    presupAviso:
      "Costos promedio orientativos para un turista de gama media (USD). Los vuelos son aproximados desde Colombia; confirma el precio real con el detector de vuelos.",
    // Diseño / etiquetas
    heroEyebrow: "Planifica tu próxima aventura",
    destinosEyebrow: "Inspiración",
    // Presupuesto · modos y ruta
    presupModoDestino: "Un destino",
    presupModoRuta: "Ruta multiciudad",
    presupRutaSub: "Arma una ruta de varias ciudades que entre en tu presupuesto",
    presupDesdeCiudad: "Saliendo desde",
    presupRutaTitulo: "Tu ruta recomendada",
    presupOtraRuta: "Otra ruta",
    presupRutaCiudades: "ciudades",
    presupRutaDias: "días",
    presupNoRuta:
      "No encontramos una ruta dentro de tu presupuesto aquí. Sube el presupuesto o los días, o elige otra región.",
    presupVueloIntl: "Vuelo internacional (ida y vuelta)",
    presupEntreCiudades: "Transporte entre ciudades",
    presupNoches: "noches",
    // Ofertas de vuelos
    ofertasEyebrow: "Alertas de precio",
    ofertasTitulo: "Vuelos baratos desde Colombia",
    ofertasSub: "Mejores precios detectados desde Bogotá y Medellín hacia el mundo, actualizados cada pocas horas.",
    ofertasTodos: "Todos",
    ofertasGanga: "Oferta",
    ofertasIdaVuelta: "ida y vuelta",
    ofertasPlanear: "Planear",
    ofertasActualizado: "Actualizado",
    ofertasHaceMin: "visto hace {n} min",
    ofertasHaceHoras: "visto hace {n} h",
    ofertasHaceDias: "visto hace {n} d",
    ofertasAprox: "Precio aproximado",
    ofertasComparar: "Comparar en Google",
    ofertasFuente: "Precios de referencia",
    todosLugares: "Todos los lugares",
    agregar: "Agregar",
    presupBuscarCiudad: "Buscar ciudad o país…",
    presupExcluidas: "Excluidas",
    presupExcluir: "Quitar esta ciudad de la ruta",
    // Asesor de viajes (chat IA)
    asesorBoton: "Asesor de viajes",
    asesorTitulo: "Brújula · Asesor de viajes",
    asesorSubtitulo: "Tu guía con IA",
    asesorSaludo: "¡Hola{nombre}! Soy Brújula 🧭, tu asesora de viajes. Cuéntame tu presupuesto, fechas o qué te gustaría conocer y te armo opciones.",
    asesorPlaceholder: "Pregúntame a dónde viajar…",
    asesorError: "Tuve un problema para responder. Intenta de nuevo.",
    asesorSinClave: "El asesor con IA aún no está activado. Para encenderlo, agrega tu clave ANTHROPIC_API_KEY en Vercel (Settings → Environment Variables) y vuelve a desplegar.",
    asesorModoGuia: "Guía gratis (sin costo)",
    asesorTabGuia: "Guía",
    asesorTabIA: "IA",
    asesorAvisoIA: "Modo IA: conversación libre con Claude. Consume créditos de la API.",
    guiaSaludo: "¡Hola{nombre}! Soy tu guía 🧭. Te armo una ruta sin costo. Primero: ¿a qué región quieres viajar?",
    guiaPreguntaPresupuesto: "¿Cuál es tu presupuesto total?",
    guiaPreguntaDias: "¿Cuántos días tienes?",
    guiaAquiRuta: "Esta ruta te cabe 👇",
    guiaSinRuta: "Con esos datos no encontré una ruta dentro del presupuesto. Prueba subir el presupuesto o los días, o elige otra región.",
    guiaVerPresupuesto: "Ver presupuesto completo",
    guiaReiniciar: "Empezar de nuevo",
    asesorEj1: "¿3 días en Lisboa?",
    asesorEj2: "¿Playa barata en diciembre?",
    asesorEj3: "¿Qué hago en Roma?",
    verMas: "Ver más",
    verMenos: "Ver menos",
    ajustarViaje: "Ajustar viaje",
    compartir: "Compartir",
    copiado: "¡Copiado!",
    miViajeA: "Mi viaje a",
    hechoCon: "Hecho con",
  },

  en: {
    tagline: "Your perfect itinerary in any city in the world",
    buscarPlaceholder: "City, Country (e.g. Madrid, Spain)",
    buscar: "Search",
    heroTitulo: "Your trip, planned in seconds",
    heroTexto:
      "Day-by-day itinerary with the best places, photos, restaurants and how to get around. All here, without leaving the app.",
    benDiaTitulo: "Day by day",
    benDiaTexto: "Splits places to fit your time",
    benGpsTitulo: "Live GPS",
    benGpsTexto: "Tells you if you're ahead or behind",
    benComerTitulo: "Eat & go out",
    benComerTexto: "Restaurants, cafés and nightlife",
    benLlegarTitulo: "How to get there",
    benLlegarTexto: "Transport, time and cost between points",
    pruebaPopular: "Try a popular destination:",
    dias: "Days",
    horasDia: "Hours/day",
    recalcular: "Recalculate",
    diurno: "Daytime",
    nocturno: "Nighttime",
    diurnoDesc: "Monuments, museums and walks",
    nocturnoDesc: "Bars, viewpoints and nightlife",
    lugares: "places",
    cat_imperdibles: "Must-see",
    cat_restaurantes: "Restaurants",
    cat_cafes: "Cafés",
    cat_bares: "Bars / Night",
    cat_miradores: "Viewpoints",
    cat_museos: "Museums",
    cat_monumentos: "Landmarks",
    cat_parques: "Parks",
    cat_estadios: "Stadiums",
    dia: "Day",
    paradas: "stops",
    enTotal: "total",
    visitas: "Visits",
    traslados: "Transfers",
    empezarGps: "Start day with GPS tracking",
    llegueSiguiente: "I reached the next one",
    terminar: "Finish",
    parada: "Stop",
    sinParadas:
      "No stops for this day with the set time. Increase hours per day or reduce the number of days.",
    cargandoLugares: "Finding the best places…",
    sinResultados:
      "We couldn't find places in this category near the center. Try another category or tap Recalculate.",
    cargando: "Loading…",
    verFoto: "See photo and how to get there",
    cambiar: "Change",
    quitar: "Remove",
    comoLlegar: "How to get there",
    desdeTuUbicacion: "from your location",
    activaGps:
      "Turn on GPS (below in the app) to see exact transport and time from where you are.",
    estasA: "You're",
    deAqui: "away. Choose how to get there:",
    desdeCentro: "from the center of",
    verRuta: "See route",
    recomendado: "recommended",
    aproxAviso:
      "Approximate times and costs. The route is drawn on the app's map.",
    activarGps: "Turn on GPS to see myself on the map and track times live",
    activo: "active",
    atrasado: "You're {n} min behind",
    adelantado: "You're {n} min ahead",
    enHora: "You're on time",
    caminar: "Walk",
    metroBus: "Metro / Bus",
    bici: "Bike",
    taxiApp: "Taxi / App",
    gratis: "Free",
    hola: "Hi",
    entrar: "Sign in",
    salir: "Sign out",
    inicio: "Home",
    tuNombre: "What's your name?",
    comenzar: "Start",
    idioma: "Language",
    footer: "Data from OpenStreetMap and Wikipedia",
    // Afiliados / reservas
    afTitulo: "Book your trip",
    afTours: "Tours & experiences",
    afToursDesc: "Guided activities near your route",
    afHoteles: "Where to stay?",
    afHotelesDesc: "Hotels near your itinerary",
    afVuelos: "Flights",
    afVuelosDesc: "Find flights to your destination",
    afReservar: "See options",
    afTourCerca: "Book a tour nearby",
    afNota: "Some links are affiliate links: if you book, we may earn a commission at no extra cost to you.",
    saludoManana: "Good morning",
    saludoTarde: "Good afternoon",
    saludoNoche: "Good evening",
    presupEyebrow: "Plan by budget",
    presupBoton: "Where can I travel on my budget?",
    presupTitulo: "Travel within your budget",
    presupSub: "See where you can go with what you have",
    presupTuPresup: "Your total budget",
    presupPersonas: "People",
    presupPersonaS: "person",
    presupPersonasP: "people",
    presupRegion: "Which region?",
    presupDestinos: "destinations within reach",
    presupVuelo: "Flight (round trip)",
    presupHospedaje: "Accommodation",
    presupComida: "Food",
    presupTransporte: "Local transport",
    presupExtras: "Activities & extras",
    presupTeSobra: "You'd have left",
    presupTeFalta: "You're short",
    presupAlcanza: "enough for",
    presupPlanear: "Plan",
    presupVerVuelos: "Flights",
    presupAviso:
      "Average estimated costs for a mid-range tourist (USD). Flights are approximate from Colombia; confirm the real price with the flight detector.",
    heroEyebrow: "Plan your next adventure",
    destinosEyebrow: "Inspiration",
    presupModoDestino: "One destination",
    presupModoRuta: "Multi-city route",
    presupRutaSub: "Build a multi-city route that fits your budget",
    presupDesdeCiudad: "Departing from",
    presupRutaTitulo: "Your recommended route",
    presupOtraRuta: "Another route",
    presupRutaCiudades: "cities",
    presupRutaDias: "days",
    presupNoRuta:
      "We couldn't find a route within your budget here. Raise the budget or days, or pick another region.",
    presupVueloIntl: "International flight (round trip)",
    presupEntreCiudades: "Inter-city transport",
    presupNoches: "nights",
    ofertasEyebrow: "Price alerts",
    ofertasTitulo: "Cheap flights from Colombia",
    ofertasSub: "Best fares detected from Bogotá and Medellín, refreshed every few hours.",
    ofertasTodos: "All",
    ofertasGanga: "Deal",
    ofertasIdaVuelta: "round trip",
    ofertasPlanear: "Plan",
    ofertasActualizado: "Updated",
    ofertasHaceMin: "seen {n} min ago",
    ofertasHaceHoras: "seen {n} h ago",
    ofertasHaceDias: "seen {n} d ago",
    ofertasAprox: "Approx. price",
    ofertasComparar: "Compare on Google",
    ofertasFuente: "Reference prices",
    todosLugares: "All places",
    agregar: "Add",
    presupBuscarCiudad: "Search city or country…",
    presupExcluidas: "Excluded",
    presupExcluir: "Remove this city from the route",
    asesorBoton: "Travel advisor",
    asesorTitulo: "Compass · Travel advisor",
    asesorSubtitulo: "Your AI guide",
    asesorSaludo: "Hi{nombre}! I'm Compass 🧭, your travel advisor. Tell me your budget, dates or what you'd like to see and I'll put together options.",
    asesorPlaceholder: "Ask me where to travel…",
    asesorError: "I had a problem responding. Try again.",
    asesorSinClave: "The AI advisor isn't enabled yet. To turn it on, add your ANTHROPIC_API_KEY in Vercel (Settings → Environment Variables) and redeploy.",
    asesorModoGuia: "Free guide (no cost)",
    asesorTabGuia: "Guide",
    asesorTabIA: "AI",
    asesorAvisoIA: "AI mode: free chat with Claude. Uses API credits.",
    guiaSaludo: "Hi{nombre}! I'm your guide 🧭. I'll build you a route for free. First: which region do you want to travel to?",
    guiaPreguntaPresupuesto: "What's your total budget?",
    guiaPreguntaDias: "How many days do you have?",
    guiaAquiRuta: "This route fits 👇",
    guiaSinRuta: "With that I couldn't find a route within budget. Try raising the budget or days, or pick another region.",
    guiaVerPresupuesto: "See full budget",
    guiaReiniciar: "Start over",
    asesorEj1: "3 days in Lisbon?",
    asesorEj2: "Cheap beach in December?",
    asesorEj3: "What to do in Rome?",
    verMas: "See more",
    verMenos: "See less",
    ajustarViaje: "Adjust trip",
    compartir: "Share",
    copiado: "Copied!",
    miViajeA: "My trip to",
    hechoCon: "Made with",
  },

  pt: {
    tagline: "Seu roteiro perfeito em qualquer cidade do mundo",
    buscarPlaceholder: "Cidade, País (ex. Madri, Espanha)",
    buscar: "Buscar",
    heroTitulo: "Sua viagem, planejada em segundos",
    heroTexto:
      "Roteiro dia a dia com os melhores lugares, fotos, restaurantes e como se locomover. Tudo aqui, sem sair do app.",
    benDiaTitulo: "Dia a dia",
    benDiaTexto: "Distribui os lugares conforme seu tempo",
    benGpsTitulo: "GPS ao vivo",
    benGpsTexto: "Avisa se você está adiantado ou atrasado",
    benComerTitulo: "Comer e sair",
    benComerTexto: "Restaurantes, cafés e vida noturna",
    benLlegarTitulo: "Como chegar",
    benLlegarTexto: "Transporte, tempo e custo entre pontos",
    pruebaPopular: "Experimente um destino popular:",
    dias: "Dias",
    horasDia: "Horas/dia",
    recalcular: "Recalcular",
    diurno: "Diurno",
    nocturno: "Noturno",
    diurnoDesc: "Monumentos, museus e passeios",
    nocturnoDesc: "Bares, mirantes e vida noturna",
    lugares: "lugares",
    cat_imperdibles: "Imperdíveis",
    cat_restaurantes: "Restaurantes",
    cat_cafes: "Cafés",
    cat_bares: "Bares / Noite",
    cat_miradores: "Mirantes",
    cat_museos: "Museus",
    cat_monumentos: "Monumentos",
    cat_parques: "Parques",
    cat_estadios: "Estádios",
    dia: "Dia",
    paradas: "paradas",
    enTotal: "no total",
    visitas: "Visitas",
    traslados: "Deslocamentos",
    empezarGps: "Começar dia com rastreamento GPS",
    llegueSiguiente: "Cheguei no próximo",
    terminar: "Terminar",
    parada: "Parada",
    sinParadas:
      "Sem paradas para este dia com o tempo configurado. Aumente as horas por dia ou reduza o número de dias.",
    cargandoLugares: "Buscando os melhores lugares…",
    sinResultados:
      "Não encontramos lugares desta categoria perto do centro. Tente outra categoria ou toque em Recalcular.",
    cargando: "Carregando…",
    verFoto: "Ver foto e como chegar",
    cambiar: "Trocar",
    quitar: "Remover",
    comoLlegar: "Como chegar",
    desdeTuUbicacion: "da sua localização",
    activaGps:
      "Ative o GPS (abaixo no app) para ver o transporte e o tempo exatos de onde você está.",
    estasA: "Você está a",
    deAqui: "daqui. Escolha como chegar:",
    desdeCentro: "do centro de",
    verRuta: "Ver rota",
    recomendado: "recomendado",
    aproxAviso:
      "Tempos e custos aproximados. A rota é desenhada no mapa do app.",
    activarGps: "Ativar GPS para me ver no mapa e calcular tempos ao vivo",
    activo: "ativo",
    atrasado: "Você está {n} min atrasado",
    adelantado: "Você está {n} min adiantado",
    enHora: "Você está no horário",
    caminar: "Caminhar",
    metroBus: "Metrô / Ônibus",
    bici: "Bike",
    taxiApp: "Táxi / App",
    gratis: "Grátis",
    hola: "Olá",
    entrar: "Entrar",
    salir: "Sair",
    inicio: "Início",
    tuNombre: "Como você se chama?",
    comenzar: "Começar",
    idioma: "Idioma",
    footer: "Dados do OpenStreetMap e Wikipedia",
    // Afiliados / reservas
    afTitulo: "Reserve sua viagem",
    afTours: "Tours e experiências",
    afToursDesc: "Atividades com guia perto da sua rota",
    afHoteles: "Onde ficar?",
    afHotelesDesc: "Hotéis perto do seu itinerário",
    afVuelos: "Voos",
    afVuelosDesc: "Encontre voos para o seu destino",
    afReservar: "Ver opções",
    afTourCerca: "Reserve um tour por perto",
    afNota: "Alguns links são de afiliados: se você reservar, podemos ganhar uma comissão sem custo extra para você.",
    saludoManana: "Bom dia",
    saludoTarde: "Boa tarde",
    saludoNoche: "Boa noite",
    presupEyebrow: "Planeje por orçamento",
    presupBoton: "Para onde viajar com meu orçamento?",
    presupTitulo: "Viaje com seu orçamento",
    presupSub: "Veja aonde você pode ir com o que tem",
    presupTuPresup: "Seu orçamento total",
    presupPersonas: "Pessoas",
    presupPersonaS: "pessoa",
    presupPersonasP: "pessoas",
    presupRegion: "Qual região?",
    presupDestinos: "destinos ao seu alcance",
    presupVuelo: "Voo (ida e volta)",
    presupHospedaje: "Hospedagem",
    presupComida: "Comida",
    presupTransporte: "Transporte local",
    presupExtras: "Atividades e extras",
    presupTeSobra: "Sobraria",
    presupTeFalta: "Faltam",
    presupAlcanza: "dá para",
    presupPlanear: "Planejar",
    presupVerVuelos: "Voos",
    presupAviso:
      "Custos médios estimados para um turista intermediário (USD). Os voos são aproximados desde a Colômbia; confirme o preço real com o detector de voos.",
    heroEyebrow: "Planeje sua próxima aventura",
    destinosEyebrow: "Inspiração",
    presupModoDestino: "Um destino",
    presupModoRuta: "Rota multicidades",
    presupRutaSub: "Monte uma rota de várias cidades que caiba no seu orçamento",
    presupDesdeCiudad: "Saindo de",
    presupRutaTitulo: "Sua rota recomendada",
    presupOtraRuta: "Outra rota",
    presupRutaCiudades: "cidades",
    presupRutaDias: "dias",
    presupNoRuta:
      "Não encontramos uma rota dentro do seu orçamento aqui. Aumente o orçamento ou os dias, ou escolha outra região.",
    presupVueloIntl: "Voo internacional (ida e volta)",
    presupEntreCiudades: "Transporte entre cidades",
    presupNoches: "noites",
    ofertasEyebrow: "Alertas de preço",
    ofertasTitulo: "Voos baratos da Colômbia",
    ofertasSub: "Melhores preços detectados de Bogotá e Medellín, atualizados a cada poucas horas.",
    ofertasTodos: "Todos",
    ofertasGanga: "Oferta",
    ofertasIdaVuelta: "ida e volta",
    ofertasPlanear: "Planejar",
    ofertasActualizado: "Atualizado",
    ofertasHaceMin: "visto há {n} min",
    ofertasHaceHoras: "visto há {n} h",
    ofertasHaceDias: "visto há {n} d",
    ofertasAprox: "Preço aproximado",
    ofertasComparar: "Comparar no Google",
    ofertasFuente: "Preços de referência",
    todosLugares: "Todos os lugares",
    agregar: "Adicionar",
    presupBuscarCiudad: "Buscar cidade ou país…",
    presupExcluidas: "Excluídas",
    presupExcluir: "Remover esta cidade da rota",
    asesorBoton: "Consultor de viagens",
    asesorTitulo: "Bússola · Consultor de viagens",
    asesorSubtitulo: "Seu guia com IA",
    asesorSaludo: "Olá{nombre}! Sou a Bússola 🧭, sua consultora de viagens. Conte seu orçamento, datas ou o que gostaria de conhecer e eu monto opções.",
    asesorPlaceholder: "Pergunte para onde viajar…",
    asesorError: "Tive um problema para responder. Tente de novo.",
    asesorSinClave: "O consultor com IA ainda não está ativado. Para ligá-lo, adicione sua ANTHROPIC_API_KEY no Vercel (Settings → Environment Variables) e publique de novo.",
    asesorModoGuia: "Guia grátis (sem custo)",
    asesorTabGuia: "Guia",
    asesorTabIA: "IA",
    asesorAvisoIA: "Modo IA: conversa livre com Claude. Consome créditos da API.",
    guiaSaludo: "Olá{nombre}! Sou seu guia 🧭. Monto uma rota sem custo. Primeiro: para qual região quer viajar?",
    guiaPreguntaPresupuesto: "Qual é seu orçamento total?",
    guiaPreguntaDias: "Quantos dias você tem?",
    guiaAquiRuta: "Esta rota cabe 👇",
    guiaSinRuta: "Com isso não encontrei uma rota dentro do orçamento. Tente aumentar o orçamento ou os dias, ou escolha outra região.",
    guiaVerPresupuesto: "Ver orçamento completo",
    guiaReiniciar: "Começar de novo",
    asesorEj1: "3 dias em Lisboa?",
    asesorEj2: "Praia barata em dezembro?",
    asesorEj3: "O que fazer em Roma?",
    verMas: "Ver mais",
    verMenos: "Ver menos",
    ajustarViaje: "Ajustar viagem",
    compartir: "Compartilhar",
    copiado: "Copiado!",
    miViajeA: "Minha viagem a",
    hechoCon: "Feito com",
  },

  fr: {
    tagline: "Votre itinéraire parfait dans n'importe quelle ville du monde",
    buscarPlaceholder: "Ville, Pays (ex. Madrid, Espagne)",
    buscar: "Rechercher",
    heroTitulo: "Votre voyage, planifié en quelques secondes",
    heroTexto:
      "Itinéraire jour par jour avec les meilleurs lieux, photos, restaurants et comment se déplacer. Tout ici, sans quitter l'app.",
    benDiaTitulo: "Jour par jour",
    benDiaTexto: "Répartit les lieux selon votre temps",
    benGpsTitulo: "GPS en direct",
    benGpsTexto: "Vous dit si vous êtes en avance ou en retard",
    benComerTitulo: "Manger et sortir",
    benComerTexto: "Restaurants, cafés et vie nocturne",
    benLlegarTitulo: "Comment y aller",
    benLlegarTexto: "Transport, temps et coût entre les points",
    pruebaPopular: "Essayez une destination populaire :",
    dias: "Jours",
    horasDia: "Heures/jour",
    recalcular: "Recalculer",
    diurno: "Jour",
    nocturno: "Nuit",
    diurnoDesc: "Monuments, musées et balades",
    nocturnoDesc: "Bars, points de vue et vie nocturne",
    lugares: "lieux",
    cat_imperdibles: "Incontournables",
    cat_restaurantes: "Restaurants",
    cat_cafes: "Cafés",
    cat_bares: "Bars / Nuit",
    cat_miradores: "Points de vue",
    cat_museos: "Musées",
    cat_monumentos: "Monuments",
    cat_parques: "Parcs",
    cat_estadios: "Stades",
    dia: "Jour",
    paradas: "arrêts",
    enTotal: "au total",
    visitas: "Visites",
    traslados: "Trajets",
    empezarGps: "Commencer la journée avec suivi GPS",
    llegueSiguiente: "Je suis arrivé au suivant",
    terminar: "Terminer",
    parada: "Arrêt",
    sinParadas:
      "Aucun arrêt pour cette journée avec le temps configuré. Augmentez les heures par jour ou réduisez le nombre de jours.",
    cargandoLugares: "Recherche des meilleurs lieux…",
    sinResultados:
      "Aucun lieu de cette catégorie près du centre. Essayez une autre catégorie ou appuyez sur Recalculer.",
    cargando: "Chargement…",
    verFoto: "Voir la photo et l'itinéraire",
    cambiar: "Changer",
    quitar: "Retirer",
    comoLlegar: "Comment y aller",
    desdeTuUbicacion: "depuis votre position",
    activaGps:
      "Activez le GPS (en bas de l'app) pour voir le transport et le temps exacts depuis votre position.",
    estasA: "Vous êtes à",
    deAqui: "d'ici. Choisissez comment y aller :",
    desdeCentro: "du centre de",
    verRuta: "Voir l'itinéraire",
    recomendado: "recommandé",
    aproxAviso:
      "Temps et coûts approximatifs. L'itinéraire est tracé sur la carte de l'app.",
    activarGps:
      "Activer le GPS pour me voir sur la carte et calculer les temps en direct",
    activo: "actif",
    atrasado: "Vous avez {n} min de retard",
    adelantado: "Vous avez {n} min d'avance",
    enHora: "Vous êtes à l'heure",
    caminar: "Marcher",
    metroBus: "Métro / Bus",
    bici: "Vélo",
    taxiApp: "Taxi / App",
    gratis: "Gratuit",
    hola: "Bonjour",
    entrar: "Se connecter",
    salir: "Se déconnecter",
    inicio: "Accueil",
    tuNombre: "Comment vous appelez-vous ?",
    comenzar: "Commencer",
    idioma: "Langue",
    footer: "Données d'OpenStreetMap et Wikipedia",
    // Afiliados / reservas
    afTitulo: "Réservez votre voyage",
    afTours: "Visites et activités",
    afToursDesc: "Activités guidées près de votre itinéraire",
    afHoteles: "Où dormir ?",
    afHotelesDesc: "Hôtels près de votre itinéraire",
    afVuelos: "Vols",
    afVuelosDesc: "Trouvez des vols vers votre destination",
    afReservar: "Voir les options",
    afTourCerca: "Réservez une visite à proximité",
    afNota: "Certains liens sont des liens d'affiliation : si vous réservez, nous pouvons percevoir une commission sans coût supplémentaire pour vous.",
    saludoManana: "Bonjour",
    saludoTarde: "Bon après-midi",
    saludoNoche: "Bonsoir",
    presupEyebrow: "Planifier par budget",
    presupBoton: "Où voyager avec mon budget ?",
    presupTitulo: "Voyagez selon votre budget",
    presupSub: "Voyez où vous pouvez aller avec ce que vous avez",
    presupTuPresup: "Votre budget total",
    presupPersonas: "Personnes",
    presupPersonaS: "personne",
    presupPersonasP: "personnes",
    presupRegion: "Quelle région ?",
    presupDestinos: "destinations accessibles",
    presupVuelo: "Vol (aller-retour)",
    presupHospedaje: "Hébergement",
    presupComida: "Nourriture",
    presupTransporte: "Transport local",
    presupExtras: "Activités et extras",
    presupTeSobra: "Il vous resterait",
    presupTeFalta: "Il vous manque",
    presupAlcanza: "assez pour",
    presupPlanear: "Planifier",
    presupVerVuelos: "Vols",
    presupAviso:
      "Coûts moyens estimés pour un touriste de gamme moyenne (USD). Les vols sont approximatifs depuis la Colombie ; confirmez le prix réel avec le détecteur de vols.",
    heroEyebrow: "Planifiez votre prochaine aventure",
    destinosEyebrow: "Inspiration",
    presupModoDestino: "Une destination",
    presupModoRuta: "Itinéraire multi-villes",
    presupRutaSub: "Composez un itinéraire de plusieurs villes selon votre budget",
    presupDesdeCiudad: "Au départ de",
    presupRutaTitulo: "Votre itinéraire recommandé",
    presupOtraRuta: "Autre itinéraire",
    presupRutaCiudades: "villes",
    presupRutaDias: "jours",
    presupNoRuta:
      "Aucun itinéraire dans votre budget ici. Augmentez le budget ou les jours, ou choisissez une autre région.",
    presupVueloIntl: "Vol international (aller-retour)",
    presupEntreCiudades: "Transport entre villes",
    presupNoches: "nuits",
    ofertasEyebrow: "Alertes de prix",
    ofertasTitulo: "Vols pas chers depuis la Colombie",
    ofertasSub: "Meilleurs prix détectés depuis Bogotá et Medellín, actualisés toutes les quelques heures.",
    ofertasTodos: "Tous",
    ofertasGanga: "Offre",
    ofertasIdaVuelta: "aller-retour",
    ofertasPlanear: "Planifier",
    ofertasActualizado: "Mis à jour",
    ofertasHaceMin: "vu il y a {n} min",
    ofertasHaceHoras: "vu il y a {n} h",
    ofertasHaceDias: "vu il y a {n} j",
    ofertasAprox: "Prix approximatif",
    ofertasComparar: "Comparer sur Google",
    ofertasFuente: "Prix de référence",
    todosLugares: "Tous les lieux",
    agregar: "Ajouter",
    presupBuscarCiudad: "Rechercher ville ou pays…",
    presupExcluidas: "Exclues",
    presupExcluir: "Retirer cette ville de l'itinéraire",
    asesorBoton: "Conseiller voyage",
    asesorTitulo: "Boussole · Conseiller voyage",
    asesorSubtitulo: "Votre guide IA",
    asesorSaludo: "Bonjour{nombre} ! Je suis Boussole 🧭, votre conseillère voyage. Dites-moi votre budget, vos dates ou ce que vous aimeriez découvrir et je vous prépare des options.",
    asesorPlaceholder: "Demandez-moi où voyager…",
    asesorError: "J'ai eu un problème pour répondre. Réessayez.",
    asesorSinClave: "Le conseiller IA n'est pas encore activé. Pour l'activer, ajoutez votre ANTHROPIC_API_KEY dans Vercel (Settings → Environment Variables) et redéployez.",
    asesorModoGuia: "Guide gratuit (sans coût)",
    asesorTabGuia: "Guide",
    asesorTabIA: "IA",
    asesorAvisoIA: "Mode IA : conversation libre avec Claude. Consomme des crédits API.",
    guiaSaludo: "Bonjour{nombre} ! Je suis ton guide 🧭. Je te prépare un itinéraire gratuit. D'abord : vers quelle région veux-tu voyager ?",
    guiaPreguntaPresupuesto: "Quel est ton budget total ?",
    guiaPreguntaDias: "Combien de jours as-tu ?",
    guiaAquiRuta: "Cet itinéraire rentre 👇",
    guiaSinRuta: "Avec ça je n'ai pas trouvé d'itinéraire dans le budget. Augmente le budget ou les jours, ou choisis une autre région.",
    guiaVerPresupuesto: "Voir le budget complet",
    guiaReiniciar: "Recommencer",
    asesorEj1: "3 jours à Lisbonne ?",
    asesorEj2: "Plage pas chère en décembre ?",
    asesorEj3: "Que faire à Rome ?",
    verMas: "Voir plus",
    verMenos: "Voir moins",
    ajustarViaje: "Ajuster le voyage",
    compartir: "Partager",
    copiado: "Copié !",
    miViajeA: "Mon voyage à",
    hechoCon: "Fait avec",
  },
};

// Idioma por defecto según el navegador del usuario.
export function idiomaInicial() {
  if (typeof window === "undefined") return "es";
  const guardado = localStorage.getItem("idioma");
  if (guardado && T[guardado]) return guardado;
  const nav = (navigator.language || "es").slice(0, 2);
  return T[nav] ? nav : "es";
}

// Devuelve la función traductora t() para un idioma dado.
export function traductor(lang) {
  const dicc = T[lang] || T.es;
  return (clave, vars) => {
    let txt = dicc[clave] ?? T.es[clave] ?? clave;
    if (vars) for (const k in vars) txt = txt.replace(`{${k}}`, vars[k]);
    return txt;
  };
}
