"use client";

import { useMemo } from "react";

const iconoMedio = { tren: "🚆", vuelo: "✈️", bus: "🚌", ferry: "⛴️" };

function money(v) { return v == null ? "—" : `US$${Number(v).toLocaleString("en-US")}`; }
function fuente(f) { return f === "detectado" ? "Dato detectado" : f === "curado" ? "Referencia curada" : f === "estimado" ? "Estimación" : "Sin dato"; }

export default function InteligenciaViaje({ analisis, decisiones }) {
  const eliminaciones = decisiones?.eliminar || [];
  const mejor = decisiones?.mejorEliminacion;
  const alternativas = useMemo(() => (analisis?.tramos || []).map((t) => ({ ...t, opciones: t.alternativas || [] })), [analisis]);
  if (!analisis && !decisiones) return null;

  return <section className="space-y-3">
    <div className="rounded-2xl border border-violet-200 bg-violet-50 p-5 dark:border-violet-900/60 dark:bg-violet-950/20">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0 flex-1"><div className="text-[10.5px] font-bold uppercase tracking-[0.16em] text-violet-700 dark:text-violet-300">Anduve Intelligence</div><h3 className="mt-1 text-[17px] font-black text-violet-950 dark:text-violet-100">No solo calculamos tu viaje. Lo cuestionamos.</h3><p className="mt-1.5 max-w-2xl text-[12.5px] leading-relaxed text-violet-900/75 dark:text-violet-100/70">Comparamos alternativas y buscamos decisiones que puedan hacer tu ruta más barata, rápida o sencilla. Las estimaciones nunca se presentan como precios confirmados.</p></div>
      </div>

      <div className="mt-4 space-y-3">{alternativas.map((t) => <div key={t.id} className="rounded-2xl border border-white/80 bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-[13px] font-extrabold text-slate-900 dark:text-white">{t.desde} → {t.hasta}</div><span className="text-[10px] font-bold text-slate-400">{t.km ? `${Math.round(t.km)} km` : "distancia no disponible"}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-3">{t.opciones.map((o, i) => <div key={`${o.medio}-${i}`} className={`rounded-xl border p-3 ${o.recomendado ? "border-violet-300 bg-violet-50/70 dark:border-violet-800 dark:bg-violet-950/20" : "border-slate-200 dark:border-slate-700"}`}><div className="flex items-center justify-between gap-2"><span className="font-extrabold text-slate-800 dark:text-slate-100">{iconoMedio[o.medio] || "🚐"} {o.medio === "vuelo" ? "Avión" : o.medio || "Sin opción"}</span>{o.recomendado && <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[9px] font-black text-emerald-700">RECOMENDADO</span>}</div><div className="mt-2 text-[15px] font-black text-slate-900 dark:text-white">{money(o.precio)}</div><div className="text-[11px] text-slate-500">{o.puertaAPuerta_h != null ? `${o.puertaAPuerta_h} h puerta a puerta` : "Tiempo desconocido"} · {o.score != null ? `${o.score}/100` : "sin score"}</div><div className={`mt-1 text-[9.5px] font-bold ${o.fuente === "estimado" ? "text-amber-600" : "text-emerald-600"}`}>{fuente(o.fuente)}</div><p className="mt-2 text-[10.5px] leading-relaxed text-slate-500">{o.explicacion || o.nota}</p></div>)}</div></div>)}</div>

      <div className="mt-5 border-t border-violet-200/70 pt-5 dark:border-violet-900/50">{mejor ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-900/60 dark:bg-amber-950/20"><div className="text-[10px] font-black uppercase tracking-[0.15em] text-amber-700">Mayor impacto potencial</div><h4 className="mt-1 text-[15px] font-black text-amber-950 dark:text-amber-100">¿Qué pasa si eliminas {mejor.ciudad}?</h4><p className="mt-1.5 text-[12px] text-amber-900/75 dark:text-amber-100/70">{mejor.razon}</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-xl bg-white/80 p-3"><div className="text-[9px] font-bold text-slate-400">Impacto neto</div><div className={`text-[15px] font-black ${mejor.impactoNetoEstimado < 0 ? "text-red-600" : "text-slate-900"}`}>{mejor.impactoNetoEstimado < 0 ? "−" : ""}{money(Math.abs(mejor.impactoNetoEstimado))}</div></div><div className="rounded-xl bg-white/80 p-3"><div className="text-[9px] font-bold text-slate-400">Cambio en transporte</div><div className="text-[15px] font-black">{mejor.ahorroTransporteEstimado >= 0 ? "−" : "+"}{money(Math.abs(mejor.ahorroTransporteEstimado))}</div></div><div className="rounded-xl bg-white/80 p-3"><div className="text-[9px] font-bold text-slate-400">Noches de esa parada</div><div className="text-[15px] font-black">{mejor.nochesLiberadas}</div></div><div className="rounded-xl bg-white/80 p-3"><div className="text-[9px] font-bold text-slate-400">Confianza</div><div className="text-[15px] font-black capitalize">{mejor.confianza}</div></div></div><p className="mt-3 text-[10.5px] leading-relaxed text-amber-900/70 dark:text-amber-100/65">El impacto neto es orientativo: combina el cambio de transporte con el coste diario estimado de la parada. Las noches indicadas no significan necesariamente menos días de viaje; son noches que podrían reasignarse si mantienes la duración total.</p></div> : <div className="rounded-xl border border-slate-200 bg-white p-4 text-[12px] text-slate-500 dark:border-slate-700 dark:bg-slate-800">No hay una eliminación claramente beneficiosa con los datos disponibles.</div>}
        {eliminaciones.length > 1 && <div className="mt-3 space-y-2">{eliminaciones.slice(1, 4).map((d) => <div key={`${d.ciudad}-${d.indice}`} className="flex w-full items-center justify-between rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-800"><span className="text-[12px] font-extrabold">Quitar {d.ciudad}</span><span className={`text-[11px] font-bold ${d.impactoNetoEstimado < 0 ? "text-red-600" : "text-slate-500"}`}>{d.impactoNetoEstimado > 0 ? `~${money(d.impactoNetoEstimado)}` : d.impactoNetoEstimado < 0 ? `+${money(Math.abs(d.impactoNetoEstimado))}` : "sin impacto neto"} · {d.ahorroHoras >= 0 ? `−${d.ahorroHoras} h` : `+${Math.abs(d.ahorroHoras)} h`}</span></div>)}</div>}
        <p className="mt-3 text-[10.5px] text-slate-400">Estas propuestas no cambian tu ruta automáticamente. El coste diario incluye cama, comida, transporte local y ocio; por eso la estancia es una referencia de coste de viaje, no un precio puro de alojamiento.</p>
      </div>
    </div>
  </section>;
}